// Date: 10/10/2013 17:02:20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer Body1;
    ModelRenderer Head1;
    ModelRenderer Head2;
    ModelRenderer LeftFin1;
    ModelRenderer RightFin1;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Tail4;
    ModelRenderer BackFin1;
  
  public ModelModel()
  {
    textureWidth = 2000;
    textureHeight = 2000;
    
      Body1 = new ModelRenderer(this, 1000, -1);
      Body1.addBox(-70F, -120F, -130F, 80, 90, 140);
      Body1.setRotationPoint(31F, 50F, 59F);
      Body1.setTextureSize(64, 32);
      Body1.mirror = true;
      setRotation(Body1, 0F, 0F, 0F);
      Head1 = new ModelRenderer(this, 1000, 240);
      Head1.addBox(-70F, -120F, -200F, 80, 45, 140);
      Head1.setRotationPoint(31F, 52F, -11F);
      Head1.setTextureSize(64, 32);
      Head1.mirror = true;
      setRotation(Head1, -0.0371786F, 0F, 0F);
      Head2 = new ModelRenderer(this, 1000, 435);
      Head2.addBox(-70F, -121F, -130F, 74, 44, 150);
      Head2.setRotationPoint(34F, 86F, -114F);
      Head2.setTextureSize(64, 32);
      Head2.mirror = true;
      setRotation(Head2, -0.3665191F, 0F, 0F);
      LeftFin1 = new ModelRenderer(this, 1000, 750);
      LeftFin1.addBox(0F, 0F, 0F, 60, 16, 24);
      LeftFin1.setRotationPoint(42F, -50F, -40F);
      LeftFin1.setTextureSize(64, 32);
      LeftFin1.mirror = true;
      setRotation(LeftFin1, 0.5235988F, -0.8726646F, 0.3490659F);
      RightFin1 = new ModelRenderer(this, 1000, 650);
      RightFin1.addBox(0F, 0F, 0F, 60, 16, 24);
      RightFin1.setRotationPoint(-72F, -40F, 10F);
      RightFin1.setTextureSize(64, 32);
      RightFin1.mirror = true;
      setRotation(RightFin1, -0.5235988F, 0.8726646F, -0.3490659F);
      Tail1 = new ModelRenderer(this, 0, -1);
      Tail1.addBox(-36F, 0F, 0F, 72, 75, 70);
      Tail1.setRotationPoint(0F, -68F, 69F);
      Tail1.setTextureSize(64, 32);
      Tail1.mirror = true;
      setRotation(Tail1, 0F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 0, -1);
      Tail2.addBox(-30F, 2F, 70F, 64, 60, 70);
      Tail2.setRotationPoint(0F, -68F, 69F);
      Tail2.setTextureSize(64, 32);
      Tail2.mirror = true;
      setRotation(Tail2, 0F, -0.0174533F, 0F);
      Tail3 = new ModelRenderer(this, 0, -1);
      Tail3.addBox(-28F, 4F, 140F, 56, 45, 60);
      Tail3.setRotationPoint(0F, -68F, 69F);
      Tail3.setTextureSize(64, 32);
      Tail3.mirror = true;
      setRotation(Tail3, 0F, 0F, 0F);
      Tail4 = new ModelRenderer(this, 0, -1);
      Tail4.addBox(-24F, 6F, 200F, 48, 35, 50);
      Tail4.setRotationPoint(0F, -68F, 69F);
      Tail4.setTextureSize(64, 32);
      Tail4.mirror = true;
      setRotation(Tail4, 0F, 0F, 0F);
      BackFin1 = new ModelRenderer(this, 1000, 1000);
      BackFin1.addBox(-45F, 8F, 250F, 90, 25, 60);
      BackFin1.setRotationPoint(0F, -68F, 69F);
      BackFin1.setTextureSize(64, 32);
      BackFin1.mirror = true;
      setRotation(BackFin1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body1.render(f5);
    Head1.render(f5);
    Head2.render(f5);
    LeftFin1.render(f5);
    RightFin1.render(f5);
    Tail1.render(f5);
    Tail2.render(f5);
    Tail3.render(f5);
    Tail4.render(f5);
    BackFin1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
