// Date: 04/02/2013 22:49:08
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Leg5;
    ModelRenderer Leg6;
    ModelRenderer Leg7;
    ModelRenderer Leg8;
    ModelRenderer Body;
    ModelRenderer Claw1;
    ModelRenderer Claw2;
    ModelRenderer Claw3;
    ModelRenderer Claw4;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail4;
    ModelRenderer Tail3;
    ModelRenderer Tail5;
    ModelRenderer Tail6;
  
  public ModelModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Leg1 = new ModelRenderer(this, 0, 0);
      Leg1.addBox(0F, 0F, 0F, 3, 0, 1);
      Leg1.setRotationPoint(1F, 23F, 2F);
      Leg1.setTextureSize(64, 64);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0.4363323F);
      Leg2.mirror = true;
      Leg2 = new ModelRenderer(this, 0, 0);
      Leg2.addBox(0F, 0F, 0F, 3, 0, 1);
      Leg2.setRotationPoint(1F, 23F, 0F);
      Leg2.setTextureSize(64, 64);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0.4363323F);
      Leg2.mirror = false;
      Leg3 = new ModelRenderer(this, 0, 0);
      Leg3.addBox(0F, 0F, 0F, 3, 0, 1);
      Leg3.setRotationPoint(1F, 23F, -2F);
      Leg3.setTextureSize(64, 64);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0.4363323F);
      Leg4 = new ModelRenderer(this, 0, 0);
      Leg4.addBox(0F, 0F, 0F, 3, 0, 1);
      Leg4.setRotationPoint(1F, 23F, -4F);
      Leg4.setTextureSize(64, 64);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0.4363323F);
      Leg5 = new ModelRenderer(this, 0, 0);
      Leg5.addBox(-4F, 0F, 0F, 3, 0, 1);
      Leg5.setRotationPoint(1F, 22.5F, -4F);
      Leg5.setTextureSize(64, 64);
      Leg5.mirror = true;
      setRotation(Leg5, 0F, 0F, -0.4363323F);
      Leg6 = new ModelRenderer(this, 0, 0);
      Leg6.addBox(-4F, 0F, 0F, 3, 0, 1);
      Leg6.setRotationPoint(0F, 22.5F, -2F);
      Leg6.setTextureSize(64, 64);
      Leg6.mirror = true;
      setRotation(Leg6, 0F, 0F, -0.4363323F);
      Leg7 = new ModelRenderer(this, 0, 0);
      Leg7.addBox(-4F, 0F, 0F, 3, 0, 1);
      Leg7.setRotationPoint(1F, 22.5F, 0F);
      Leg7.setTextureSize(64, 64);
      Leg7.mirror = true;
      setRotation(Leg7, 0F, 0F, -0.4363323F);
      Leg8 = new ModelRenderer(this, 0, 0);
      Leg8.addBox(-4F, 0F, 0F, 3, 0, 1);
      Leg8.setRotationPoint(0F, 22.5F, 2F);
      Leg8.setTextureSize(64, 64);
      Leg8.mirror = true;
      setRotation(Leg8, 0F, 0F, -0.4363323F);
      Body = new ModelRenderer(this, 0, 55);
      Body.addBox(0F, 0F, 0F, 2, 1, 8);
      Body.setRotationPoint(-1F, 22F, -5F);
      Body.setTextureSize(64, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Claw1 = new ModelRenderer(this, 0, 50);
      Claw1.addBox(0F, 0F, 0F, 1, 1, 4);
      Claw1.setRotationPoint(-3.5F, 22.5F, -7F);
      Claw1.setTextureSize(64, 64);
      Claw1.mirror = true;
      setRotation(Claw1, 0.1745329F, 0.6981317F, 0F);
      Claw2 = new ModelRenderer(this, 0, 45);
      Claw2.addBox(-1F, 0F, 0F, 1, 1, 4);
      Claw2.setRotationPoint(3.5F, 22.5F, -7F);
      Claw2.setTextureSize(64, 64);
      Claw2.mirror = true;
      setRotation(Claw2, 0.1745329F, -0.6981317F, 0F);
      Claw3 = new ModelRenderer(this, 10, 52);
      Claw3.addBox(0F, 0F, 0F, 1, 1, 2);
      Claw3.setRotationPoint(1F, 22.5F, -7.8F);
      Claw3.setTextureSize(64, 64);
      Claw3.mirror = true;
      setRotation(Claw3, 0.1745329F, 0.1745329F, 0.3141593F);
      Claw4 = new ModelRenderer(this, 10, 47);
      Claw4.addBox(0F, 0F, 0F, 1, 1, 2);
      Claw4.setRotationPoint(-2F, 22.5F, -7.8F);
      Claw4.setTextureSize(64, 64);
      Claw4.mirror = true;
      setRotation(Claw4, 0.1745329F, -0.1745329F, -0.3141593F);
      Tail1 = new ModelRenderer(this, 56, 0);
      Tail1.addBox(-1F, 0F, 0F, 2, 1, 2);
      Tail1.setRotationPoint(0F, 22F, 2.5F);
      Tail1.setTextureSize(64, 64);
      Tail1.mirror = true;
      setRotation(Tail1, 0.5585054F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 56, 4);
      Tail2.addBox(-1F, 1.5F, 1F, 2, 1, 2);
      Tail2.setRotationPoint(0F, 22.5F, 2F);
      Tail2.setTextureSize(64, 64);
      Tail2.mirror = true;
      setRotation(Tail2, 1.396263F, 0F, 0F);
      Tail4 = new ModelRenderer(this, 56, 10);
      Tail4.addBox(-1F, 3.7F, -1F, 2, 1, 3);
      Tail4.setRotationPoint(0F, 22F, 2F);
      Tail4.setTextureSize(64, 64);
      Tail4.mirror = true;
      setRotation(Tail4, 2.792527F, 0.0416105F, 0F);
      Tail3 = new ModelRenderer(this, 56, 7);
      Tail3.addBox(-1F, 2.2F, 1F, 2, 1, 2);
      Tail3.setRotationPoint(0F, 22F, 2.5F);
      Tail3.setTextureSize(64, 64);
      Tail3.mirror = true;
      setRotation(Tail3, 1.919862F, 0F, 0F);
      Tail5 = new ModelRenderer(this, 56, 14);
      Tail5.addBox(-1F, -4.8F, -1F, 2, 1, 3);
      Tail5.setRotationPoint(0F, 22F, 2F);
      Tail5.setTextureSize(64, 64);
      Tail5.mirror = true;
      setRotation(Tail5, 0.3764925F, 0F, 0F);
      Tail6 = new ModelRenderer(this, 58, 18);
      Tail6.addBox(-0.5F, 0F, -4F, 1, 1, 2);
      Tail6.setRotationPoint(0F, 22F, 2F);
      Tail6.setTextureSize(64, 64);
      Tail6.mirror = true;
      setRotation(Tail6, -0.9599311F, 0.0416105F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Leg1.render(f5);
    Leg2.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Leg5.render(f5);
    Leg6.render(f5);
    Leg7.render(f5);
    Leg8.render(f5);
    Body.render(f5);
    Claw1.render(f5);
    Claw2.render(f5);
    Claw3.render(f5);
    Claw4.render(f5);
    Tail1.render(f5);
    Tail2.render(f5);
    Tail4.render(f5);
    Tail3.render(f5);
    Tail5.render(f5);
    Tail6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
