
package agentsmod;

import java.io.File;

import net.minecraft.block.Block;
import net.minecraft.block.BlockVine;
import net.minecraft.block.material.Material;
import net.minecraft.entity.passive.EntityPig;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemSeedFood;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.Potion;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PostInit;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid="ModConfig", name="Agent's Mod", version="Alpha")
@NetworkMod(clientSideRequired=true, serverSideRequired=false)
public class ModConfig {

	public static final String modid = "ModConfig";

	public static int hayID;
	public static int saltBlockID;
	public static int cheesemoldBlockID;
	public static int cheesemoldBlockSetID;
	public static int cheesemoldBlockFilledID;
	public static int cheesewheelBlockID;
	public static int jellyblockID;
	public static int jellyblockAppleID;
	public static int jellyblockStrawberryID;
	public static int jellyblockLemonID;
	public static int jellyblockGrapeID;
	public static int jellyblockCherryID;
	public static int jellyblockOrangeID;
	public static int jellyblockBlackcurrantID;
	public static int jellyblockRaspberryID;
	public static int jellyblockBRaspberryID;

	public static int squeezerID;
	public static int squeezerBottleID;
	public static int squeezerOliveID;
	public static int squeezerSeedID;
	public static int squeezerWhaleID;
	public static int potionmakerID;
	public static int potionmaker2ID;
	public static int potionmaker3ID;
	public static int potionmaker4ID;
	public static int fermenterID;
	public static int fermenterWaterID;
	public static int fermenterBarleyID;
	public static int fermenterBarleyDoneID;
	public static int fermenterSpiderEyeID;
	public static int fermenterSpiderEyeDoneID;
	public static int brewerID;
	public static int brewerWaterID;
	public static int brewerBeerID;
	public static int brewerBeerDoneID;
	public static int brewerBeerStrongDoneID;
	public static int brewerAleID;
	public static int brewerAleDoneID;
	public static int brewerAleStrongDoneID;
	public static int brewerCiderID;
	public static int brewerCiderDoneID;
	public static int brewerCiderStrongDoneID;
	public static int brewerEggNogID;
	public static int brewerEggNogDoneID;

	public static int brewerWineID;
	public static int brewerWineDoneID;
	public static int brewerWineStrongDoneID;
	public static int brewerWineWhiteID;
	public static int brewerWineWhiteDoneID;
	public static int brewerWineWhiteStrongDoneID;
	public static int brewerWineRedID;
	public static int brewerWineRedDoneID;
	public static int brewerWineRedStrongDoneID;

	public static int brewerVodkaID;
	public static int brewerVodkaDoneID;

	public static int fryerID;
	public static int fryerbID;
	public static int fryercID;
	public static int fryerdID;
	public static int fryereID;
	public static int fryerfID;
	public static int fryerbetterID;
	public static int fryerbetterbID;
	public static int fryerbettercID;
	public static int fryerbetterdID;
	public static int fryerbettereID;
	public static int fryerbetterfID;
	public static int fryerbettergID;
	public static int fryerbetterhID;
	public static int fryerbetteriID;
	public static int fryerbetterjID;
	public static int fryerbetterkID;

	public static int rackID;
	public static int rackbID;
	public static int rackWeedID;
	public static int rackWeedbID;
	public static int rackWeedDryID;
	public static int rackWeedDrybID;
	public static int rackTobaccoID;
	public static int rackTobaccobID;
	public static int rackTobaccoDryID;
	public static int rackTobaccoDrybID;
	public static int rackPigskinID;
	public static int rackPigskinbID;
	public static int rackLeatherID;
	public static int rackLeatherbID;
	public static int rackSeaweedID;
	public static int rackSeaweedbID;
	public static int rackSeaweedDryID;
	public static int rackSeaweedDrybID;

	public static int gumballID;
	public static int gumballbID;
	public static int gumballcID;
	public static int gumballdID;
	public static int gumballeID;
	public static int gumballfID;
	public static int gumballgID;
	public static int gumballhID;

	public static int planksID;

	public static int vinerackID;
	public static int vinerackbID;
	public static int vinerackcID;
	public static int vinerackdID;

	public static int cigarboxID;
	public static int cigarboxbID;
	public static int cigarboxcID;
	public static int cigarboxdID;
	public static int cigarboxeID;

	public static int cigarbox2ID;
	public static int cigarbox2bID;
	public static int cigarbox2cID;
	public static int cigarbox2dID;
	public static int cigarbox2eID;

	public static int cigarbox3ID;
	public static int cigarbox3bID;
	public static int cigarbox3cID;
	public static int cigarbox3dID;
	public static int cigarbox3eID;

	public static int cigarbox4ID;
	public static int cigarbox4bID;
	public static int cigarbox4cID;
	public static int cigarbox4dID;
	public static int cigarbox4eID;

	public static int seedextractorIdleID;
	public static int seedextractorActiveID;
	public static int dnaextractorIdleID;
	public static int dnaextractorActiveID;
	public static int dnafabricatorIdleID;
	public static int dnafabricatorActiveID;
	public static int elementextractorIdleID;
	public static int elementextractorActiveID;




	public static int strawberryCropID;
	public static int tomatoCropID;
	public static int weedCropID;
	public static int lettuceCropID;
	public static int bananaCropID;
	public static int cornCropID;
	public static int pepperCropID;
	public static int barleyCropID;
	public static int riceCropID;
	public static int cottonCropID;
	public static int onionCropID;
	public static int oliveCropID;
	public static int lemonCropID;
	public static int orangeCropID;
	public static int cherryCropID;
	public static int lavenderCropID;
	public static int parsleyCropID;
	public static int tobaccoCropID;
	public static int peppersCropID;
	public static int walnutCropID;
	public static int walnutHardCropID;
	public static int walnutHarderCropID;
	public static int walnutGoldCropID;
	public static int walnutDiamondCropID;
	public static int grapeCropID;
	public static int grapeCropbID;
	public static int grapeCropcID;
	public static int grapeCropdID;
	public static int garlicCropID;
	public static int chicleCropID;
	public static int peanutCropID;
	public static int mintCropID;
	public static int truffleBlockID;
	public static int truffleBlockWhiteID;
	public static int raspberryCropID;
	public static int braspberryCropID;
	public static int blackcurrantCropID;
	public static int blueberryCropID;
	public static int hopsCropID;
	public static int grapePurpleCropID;
	public static int grapePurpleCropbID;
	public static int grapePurpleCropcID;
	public static int grapePurpleCropdID;

	public static int roseCropID;
	public static int dandelionCropID;

	public static int lemonLogID;
	public static int lemonLeavesID;
	public static int lemonSaplingID;

	public static int orangeLogID;
	public static int orangeLeavesID;
	public static int orangeSaplingID;

	public static int cherryLogID;
	public static int cherryLeavesID;
	public static int cherrySaplingID;

	public static int oliveLogID;
	public static int oliveLeavesID;
	public static int oliveSaplingID;

	public static int chicleLogID;
	public static int chicleLeavesID;
	public static int chicleSaplingID;

	public static int grass1ID;
	public static int grass2ID;
	public static int grass3ID;
	public static int wetClayID;

	public static int strawberryPlantID;
	public static int weedPlantID;
	public static int lettucePlantID;
	public static int cornPlantID;
	public static int pepperPlantID;
	public static int onionPlantID;
	public static int parsleyPlantID;
	public static int lavenderPlantID;
	public static int tobaccoPlantID;
	public static int peppersPlantID;
	public static int walnutPlantID;
	public static int seaweedID;



	public static int DNAID;
	public static int DNA1ID;
	public static int DNA2ID;
	public static int DNA3ID;
	public static int DNA4ID;
	public static int DNA5ID;
	public static int DNA6ID;
	public static int DNA7ID;
	public static int DNA8ID;
	public static int DNA9ID;
	public static int DNA10ID;
	public static int DNA11ID;
	public static int DNA12ID;
	public static int DNA13ID;
	public static int DNA14ID;
	public static int DNA15ID;
	public static int DNA16ID;
	public static int DNA17ID;
	public static int DNA18ID;
	public static int DNA19ID;
	public static int DNA20ID;
	public static int DNA21ID;
	public static int DNA22ID;
	public static int DNA23ID;
	public static int DNA24ID;
	public static int DNA25ID;
	public static int DNA26ID;
	public static int DNA27ID;
	public static int DNA28ID;
	public static int DNA29ID;
	public static int DNA30ID;
	public static int DNA31ID;
	public static int DNA32ID;
	public static int DNA33ID;
	public static int DNA34ID;
	public static int DNA35ID;
	public static int DNA36ID;
	public static int DNA37ID;
	public static int DNA38ID;
	public static int DNA39ID;
	public static int DNA40ID;
	public static int DNA41ID;
	public static int DNA42ID;
	public static int DNA43ID;
	public static int DNA44ID;
	public static int DNA45ID;
	public static int DNA46ID;
	public static int DNA47ID;
	public static int DNA48ID;
	public static int DNA49ID;
	public static int DNA50ID;
	public static int DNA51ID;
	public static int DNA52ID;
	public static int DNA53ID;
	public static int DNA54ID;
	public static int DNA55ID;
	public static int DNA56ID;
	public static int DNA57ID;
	public static int DNA58ID;
	public static int DNA59ID;
	public static int DNA60ID;
	public static int DNA61ID;
	public static int DNA62ID;
	public static int DNA63ID;
	public static int DNA64ID;
	public static int DNA65ID;
	public static int DNA66ID;
	public static int DNA67ID;
	public static int DNA68ID;
	public static int DNA69ID;
	public static int DNA70ID;
	public static int DNA71ID;
	public static int DNA72ID;
	public static int DNA73ID;
	public static int DNA74ID;
	public static int DNA75ID;
	public static int DNA76ID;
	public static int DNA77ID;
	public static int DNA78ID;



	public static int cheesemoldID;
	public static int cheesemoldFilledID;
	public static int cheesemoldSetID;

	public static int strawID;
	public static int stalkID;
	public static int wheatgrainID;
	public static int barleygrainID;
	public static int barleymaltID;
	public static int flourID;
	public static int doughID;
	public static int pastaID;
	public static int pastryID;
	public static int doughbreadID;
	public static int magicyeastID;
	public static int yeastID;
	public static int cheesecurdID;
	public static int lardID;
	public static int butterID;
	public static int creamID;
	public static int caramelID;
	public static int cheeseID;

	public static int doughbiscuitID;
	public static int doughbiscuitchocolateID;
	public static int doughbiscuitcaramelID;
	public static int doughbiscuitfruitID;
	public static int doughbiscuitpeanutbutterID;
	public static int biscuitID;
	public static int biscuitchocolateID;
	public static int biscuitcaramelID;
	public static int biscuitfruitID;
	public static int biscuitcreamID;
	public static int biscuitjaffaID;
	public static int biscuitpeanutbutterID;

	public static int saltID;
	public static int pepperID;
	public static int peppersaltID;

	public static int bakedbreadID;
	public static int burntbreadID;
	public static int buttieporkID;
	public static int buttiebeefID;
	public static int buttiefishID;
	public static int buttiesalamiID;
	public static int buttiecheeseID;
	public static int buttiechickenID;
	public static int buttielambID;
	public static int buttiemammothID;
	public static int buttiebaconID;
	public static int buttieeggID;
	public static int buttiejamID;
	public static int buttiemarmaladeID;
	public static int buttiepeanutbutterID;
	public static int buttiepbjID;
	public static int jamtoastID;
	public static int jamorangetoastID;
	public static int toastID;

	public static int pizzacheeseID;
	public static int pizzacheesestuffedID;
	public static int pepperonisliceID;
	public static int cheesesliceID;
	public static int breadsliceID;
	public static int pizzadoughID;
	public static int pizzabaseID;
	public static int pizzadoughstuffedID;
	public static int pizzabasestuffedID;
	public static int pizzapepperoniID;
	public static int pizzapepperonibaseID;
	public static int pizzapepperonistuffedID;
	public static int pizzapepperonibasestuffedID;
	public static int pizzacheesyID;
	public static int pizzacheesybaseID;
	public static int pizzacheesystuffedID;
	public static int pizzacheesybasestuffedID;
	public static int pizzameatID;
	public static int pizzameatbaseID;
	public static int pizzameatstuffedID;
	public static int pizzameatbasestuffedID;
	public static int pizzaamericaID;
	public static int pizzaamericabaseID;
	public static int pizzaamericastuffedID;
	public static int pizzaamericabasestuffedID;
	public static int pizzamushroomID;
	public static int pizzamushroombaseID;
	public static int pizzamushroomstuffedID;
	public static int pizzamushroombasestuffedID;
	public static int pizzavegID;
	public static int pizzavegbaseID;
	public static int pizzavegstuffedID;
	public static int pizzavegbasestuffedID;
	public static int gbreaddoughID;
	public static int gbreadID;

	public static int baconRawID;
	public static int baconCookedID;
	public static int ribsID;
	public static int ribsCookedID;
	public static int mammothmeatRawID;
	public static int mammothmeatCookedID;
	public static int lambRawID;
	public static int lambCookedID;
	public static int sausageID;
	public static int sausageCookedID;
	public static int pepperoniID;
	public static int pigskinID;
	public static int porkscratchingID;
	public static int ribsCookedKID;
	public static int lambCookedKID;
	public static int chickenCookedKID;
	public static int porkCookedKID;
	public static int beefCookedKID;
	public static int fishCookedKID;

	public static int cheesewheelID;
	public static int eggFriedID;
	public static int eggScrambledID;
	public static int eggBoiledID;
	public static int saladID;
	public static int saladChickenID;
	public static int saladEggID;
	public static int saladFruitID;
	public static int seaweedDryID;
	public static int sushiID;

	public static int soupTomatoID;
	public static int soupPumpkinID;
	public static int soupChickenID;
	public static int soupBeefID;
	public static int soupVegetableID;
	public static int soupCarrotID;

	public static int potatoSliceID;
	public static int potatoWedgeID;
	public static int crispsID;
	public static int chipsID;
	public static int svchipsID;
	public static int chippackID;
	public static int friedfishID;
	public static int friedsausageID;
	public static int friedspamID;
	public static int fishcakeID;
	public static int friedfishcakeID;
	public static int friedchickenID;
	public static int friedchickenpackID;
	public static int bunID;
	public static int burgerRawID;
	public static int burgerCookedID;
	public static int burgerRegularID;
	public static int burgerChickenID;
	public static int burgerCheeseID;
	public static int burgerBaconID;
	public static int burgerBaconCheeseID;
	public static int burgerRegularKID;
	public static int burgerChickenKID;
	public static int burgerCheeseKID;
	public static int burgerBaconKID;
	public static int burgerBaconCheeseKID;
	public static int hotdogID;
	public static int hotdogketchupID;

	public static int icecreamID;
	public static int cicecreamID;
	public static int cookiedoughID;
	public static int cdicecreamID;
	public static int sicecreamID;
	public static int blueberryicecreamID;
	public static int blackcurranticecreamID;
	public static int raspberryicecreamID;
	public static int braspberryicecreamID;
	public static int micecreamID;
	public static int licecreamID;
	public static int bubblegumicecreamID;
	public static int caramelicecreamID;
	public static int nuticecreamID;
	public static int chicecreamID;
	public static int minticecreamID;
	public static int cminticecreamID;
	public static int chocolateID;
	public static int waferID;
	public static int jellyID;
	public static int jellyAppleID;
	public static int jellyStrawberryID;
	public static int jellyLemonID;
	public static int jellyGrapeID;
	public static int jellyCherryID;
	public static int jellyOrangeID;
	public static int jellyBlackcurrantID;
	public static int jellyRaspberryID;
	public static int jellyBRaspberryID;
	public static int gumID;
	public static int gumAppleID;
	public static int gumStrawberryID;
	public static int gumLemonID;
	public static int gumGrapeID;
	public static int gumCherryID;
	public static int gumOrangeID;
	public static int gumMelonID;
	public static int gumSweetID;
	public static int gumMintID;
	public static int gumBlueberryID;
	public static int gumBlackcurrantID;
	public static int gumRaspberryID;
	public static int gumBRaspberryID;

	public static int pieAppleID;
	public static int pieCherryID;
	public static int pieBlueberryID;
	public static int pieCreamID;
	public static int pieChickenID;
	public static int pieMeatID;
	public static int piePorkID;
	public static int pieShepherdsID;
	public static int pieAppleCookedID;
	public static int pieCherryCookedID;
	public static int pieCreamCookedID;
	public static int pieChickenCookedID;
	public static int pieMeatCookedID;
	public static int piePorkCookedID;
	public static int pieShepherdsCookedID;
	public static int pieBlueberryCookedID;

	public static int packID;
	public static int cornoncobID;
	public static int popcornID;
	public static int popcornpackID;
	public static int toffeeappleID;

	public static int cupID;
	public static int jarID;
	public static int winecupID;
	public static int tankardID;
	public static int mugID;
	public static int vinegarID;
	public static int jamID;
	public static int jamOrangeID;
	public static int peanutbutterID;
	public static int treacleID;
	public static int custardID;
	public static int ketchupID;
	public static int bbqID;
	public static int mayoID;
	public static int garlicsauceID;
	public static int gravyID;
	public static int saladcreamID;
	public static int mintsauceID;
	public static int orangejuiceID;
	public static int applejuiceID;
	public static int lemonjuiceID;
	public static int grapejuiceID;
	public static int melonjuiceID;
	public static int cherryjuiceID;
	public static int blackcurrantjuiceID;
	public static int blueberryjuiceID;
	public static int raspberryjuiceID;
	public static int braspberryjuiceID;
	public static int strawberryjuiceID;
	public static int lemonadeID;
	public static int cherryadeID;
	public static int orangeadeID;
	public static int appleadeID;
	public static int blackcurrantadeID;
	public static int hotchocolatemilkID;
	public static int chocolatemilkID;

	public static int beerbasicBucketID;
	public static int beerbasicID;
	public static int beerstrongBucketID;
	public static int beerstrongID;
	public static int aleBucketID;
	public static int aleID;
	public static int alestrongBucketID;
	public static int alestrongID;
	public static int ciderBucketID;
	public static int ciderID;
	public static int ciderstrongBucketID;
	public static int ciderstrongID;
	public static int eggnogBucketID;
	public static int eggnogID;

	public static int winebasicBucketID;
	public static int winebasicID;
	public static int winestrongBucketID;
	public static int winestrongID;
	public static int winewhiteBucketID;
	public static int winewhiteID;
	public static int winewhitestrongBucketID;
	public static int winewhitestrongID;
	public static int wineredBucketID;
	public static int wineredID;
	public static int wineredstrongBucketID;
	public static int wineredstrongID;

	public static int vodkabasicBucketID;
	public static int vodkabasicID;

	public static int goldcookieID;
	public static int co2ID;
	public static int bottleAirID;



	public static int organicfuelID;
	public static int organicfuel2ID;
	public static int organicfuel3ID;
	public static int organicfuelBlockID;
	public static int organicfuelBlock2ID;
	public static int organicfuelBlock3ID;
	public static int firefuelID;
	public static int firefuel2ID;
	public static int firefuel3ID;
	public static int firefuelBlockID;
	public static int firefuelBlock2ID;
	public static int firefuelBlock3ID;


	// The instance of your mod that Forge uses.
	@Instance("ModConfig")
	public static ModConfig instance;
	// This loads up your common and client proxies. change the location of the proxies and the public static to fit your setup
	@SidedProxy(clientSide="agentsmod.ClientProxy", serverSide="agentsmod.CommonProxy")
	public static CommonProxy proxy;


	@PreInit
	public void preInit(FMLPreInitializationEvent event)
	{
		Configuration config = new Configuration(new File("config/AgentsAgriculture"));
		config.load();



		saltBlockID = config.getBlock("Blocks", "Salty Sand", 2000).getInt();
		hayID = config.getBlock("Blocks", "Straw Bale", 2001).getInt();
		cheesemoldBlockID = config.getBlock("Blocks", "Empty Cheese Mold (Block)", 2002).getInt();
		cheesemoldBlockFilledID = config.getBlock("Blocks", "Filled Cheese Mold (Block)", 2003).getInt();
		cheesemoldBlockSetID = config.getBlock("Blocks", "Set Cheese Mold (Block)", 2004).getInt();
		cheesewheelBlockID = config.getBlock("Blocks", "Cheese Wheel (Block)", 2005).getInt();
		jellyblockID = config.getBlock("Blocks", "Jelly", 2006).getInt();
		jellyblockAppleID = config.getBlock("Blocks", "Jelly (Apple)", 2007).getInt();
		jellyblockStrawberryID = config.getBlock("Blocks", "Jelly (Strawberry)", 2008).getInt();
		jellyblockLemonID = config.getBlock("Blocks", "Jelly (Lemon)", 2009).getInt();
		jellyblockGrapeID = config.getBlock("Blocks", "Jelly (Grape)", 2010).getInt();
		jellyblockCherryID = config.getBlock("Blocks", "Jelly (Cherry)", 2011).getInt();
		jellyblockOrangeID = config.getBlock("Blocks", "Jelly (Orange)", 2012).getInt();
		jellyblockBlackcurrantID = config.getBlock("Blocks", "Jelly (Blackcurrant", 2013).getInt();
		jellyblockRaspberryID = config.getBlock("Blocks", "Jelly (Raspberry)", 2014).getInt();
		jellyblockBRaspberryID = config.getBlock("Blocks", "Jelly (Blue Raspberry)", 2015).getInt();
		squeezerID = config.getBlock("Blocks", "Squeezer", 2016).getInt();
		potionmakerID = config.getBlock("Blocks", "Potion Mixer", 2017).getInt();
		fermenterID = config.getBlock("Blocks", "Fermenting Barrel", 2018).getInt();
		fermenterWaterID = config.getBlock("Blocks", "Fermenting Barrel (Water)", 2019).getInt();
		fermenterBarleyID = config.getBlock("Blocks", "Fermenting Barrel (Barley)", 2020).getInt();
		fermenterBarleyDoneID = config.getBlock("Blocks", "Fermenting Barrel (Barley - Fermented)", 2021).getInt();
		fermenterSpiderEyeID = config.getBlock("Blocks", "Fermenting Barrel (Spider Eye)", 2022).getInt();
		fermenterSpiderEyeDoneID = config.getBlock("Blocks", "Fermenting Barrel (Spider Eye - Fermented)", 2023).getInt();
		brewerID = config.getBlock("Blocks", "Brewing Barrel", 2024).getInt();
		brewerWaterID = config.getBlock("Blocks", "Brewing Barrel (Water)", 2025).getInt();
		brewerBeerID = config.getBlock("Blocks", "Brewing Barrel (Beer)", 2026).getInt();
		brewerBeerDoneID = config.getBlock("Blocks", "Brewing Barrel (Beer - Brewed)", 2027).getInt();
		brewerBeerStrongDoneID = config.getBlock("Blocks", "Brewing Barrel (Strong Beer)", 2028).getInt();
		brewerAleID = config.getBlock("Blocks", "Brewing Barrel (Ale)", 2029).getInt();
		brewerAleDoneID = config.getBlock("Blocks", "Brewing Barrel (Ale - Brewed)", 2030).getInt();
		brewerAleStrongDoneID = config.getBlock("Blocks", "Brewing Barrel (Strong Ale)", 2031).getInt();
		brewerCiderID = config.getBlock("Blocks", "Brewing Barrel (Cider)", 2032).getInt();
		brewerCiderDoneID = config.getBlock("Blocks", "Brewing Barrel (Cider - Brewed)", 2033).getInt();
		brewerCiderStrongDoneID = config.getBlock("Blocks", "Brewing Barrel (Strong Cider)", 2034).getInt();
		brewerEggNogID = config.getBlock("Blocks", "Brewing Barrel (Eggnog)", 2035).getInt();
		brewerEggNogDoneID = config.getBlock("Blocks", "Brewing Barrel (Eggnog - Brewed)", 2036).getInt();
		brewerWineID = config.getBlock("Blocks", "Brewing Barrel (Wine)", 2037).getInt();
		brewerWineDoneID = config.getBlock("Blocks", "Brewing Barrel (Wine - Brewed)", 2038).getInt();
		brewerWineStrongDoneID = config.getBlock("Blocks", "Brewing Barrel (Strong Wine)", 2039).getInt();
		brewerWineWhiteID = config.getBlock("Blocks", "Brewing Barrel (White Wine)", 2040).getInt();
		brewerWineWhiteDoneID = config.getBlock("Blocks", "Brewing Barrel (White Wine - Brewed)", 2041).getInt();
		brewerWineWhiteStrongDoneID = config.getBlock("Blocks", "Brewing Barrel (Strong White Wine)", 2042).getInt();
		brewerWineRedID = config.getBlock("Blocks", "Brewing Barrel (Red Wine)", 2043).getInt();
		brewerWineRedDoneID = config.getBlock("Blocks", "Brewing Barrel (Red Wine - Brewed)", 2044).getInt();
		brewerWineRedStrongDoneID = config.getBlock("Blocks", "Brewing Barrel (Strong Red Wine)", 2045).getInt();
		brewerVodkaID = config.getBlock("Blocks", "Brewing Barrel (Vodka)", 2046).getInt();
		brewerVodkaDoneID = config.getBlock("Blocks", "Brewing Barrel (Vodka - Brewed)", 2047).getInt();
		fryerID = config.getBlock("Blocks", "Fryer", 2048).getInt();
		rackID = config.getBlock("Blocks", "Drying Rack", 2049).getInt();
		rackbID = config.getBlock("Blocks", "Drying Rack (2)", 2050).getInt();
		rackPigskinID = config.getBlock("Blocks", "Drying Rack (Pigskin)", 2051).getInt();
		rackPigskinbID = config.getBlock("Blocks", "Drying Rack (Pigskin) (2)", 2052).getInt();
		rackLeatherID = config.getBlock("Blocks", "Drying Rack (Leather)", 2053).getInt();
		rackLeatherbID = config.getBlock("Blocks", "Drying Rack (Leather) (2)", 2054).getInt();
		rackWeedID = config.getBlock("Blocks", "Drying Rack (Cannabis)", 2055).getInt();
		rackWeedbID = config.getBlock("Blocks", "Drying Rack (Cannabis) (2)", 2056).getInt();
		rackTobaccoID = config.getBlock("Blocks", "Drying Rack (Tobacco)", 2057).getInt();
		rackTobaccobID = config.getBlock("Blocks", "Drying Rack (Tobacco) (2)", 2058).getInt();
		gumballID = config.getBlock("Blocks", "Gumball Machine (Empty)", 2059).getInt();
		gumballbID = config.getBlock("Blocks", "Gumball Machine (1)", 2060).getInt();
		gumballcID = config.getBlock("Blocks", "Gumball Machine (2)", 2061).getInt();
		gumballdID = config.getBlock("Blocks", "Gumball Machine (3)", 2062).getInt();
		gumballeID = config.getBlock("Blocks", "Gumball Machine (4)", 2063).getInt();
		gumballfID = config.getBlock("Blocks", "Gumball Machine (5)", 2064).getInt();
		gumballgID = config.getBlock("Blocks", "Gumball Machine (6)", 2065).getInt();
		gumballhID = config.getBlock("Blocks", "Gumball Machine (Filled)", 2066).getInt();
		vinerackID = config.getBlock("Blocks", "Lattice", 2067).getInt();
		vinerackbID = config.getBlock("Blocks", "Lattice (2)", 2068).getInt();
		vinerackcID = config.getBlock("Blocks", "Lattice (3)", 2069).getInt();
		vinerackdID = config.getBlock("Blocks", "Lattice (4)", 2070).getInt();
		cigarboxID = config.getBlock("Blocks", "Cigar Box (Empty)", 2071).getInt();
		cigarboxbID = config.getBlock("Blocks", "Cigar Box (1 Cigar)", 2072).getInt();
		cigarboxcID = config.getBlock("Blocks", "Cigar Box (2 Cigar)", 2073).getInt();
		cigarboxdID = config.getBlock("Blocks", "Cigar Box (3 Cigar)", 2074).getInt();
		cigarboxeID = config.getBlock("Blocks", "Cigar Box (Filled)", 2075).getInt();
		cigarbox2ID = config.getBlock("Blocks", "Cigar Box (Empty)", 2076).getInt();
		cigarbox2bID = config.getBlock("Blocks", "Cigar Box (1 Cigar)", 2077).getInt();
		cigarbox2cID = config.getBlock("Blocks", "Cigar Box (2 Cigar)", 2078).getInt();
		cigarbox2dID = config.getBlock("Blocks", "Cigar Box (3 Cigar)", 2079).getInt();
		cigarbox2eID = config.getBlock("Blocks", "Cigar Box (Filled)", 2080).getInt();
		cigarbox3ID = config.getBlock("Blocks", "Cigar Box (Empty)", 2081).getInt();
		cigarbox3bID = config.getBlock("Blocks", "Cigar Box (1 Cigar)", 2082).getInt();
		cigarbox3cID = config.getBlock("Blocks", "Cigar Box (2 Cigar)", 2083).getInt();
		cigarbox3dID = config.getBlock("Blocks", "Cigar Box (3 Cigar)", 2084).getInt();
		cigarbox3eID = config.getBlock("Blocks", "Cigar Box (Filled)", 2085).getInt();
		cigarbox4ID = config.getBlock("Blocks", "Cigar Box (Empty)", 2086).getInt();
		cigarbox4bID = config.getBlock("Blocks", "Cigar Box (1 Cigar)", 2087).getInt();
		cigarbox4cID = config.getBlock("Blocks", "Cigar Box (2 Cigar)", 2088).getInt();
		cigarbox4dID = config.getBlock("Blocks", "Cigar Box (3 Cigar)", 2089).getInt();
		cigarbox4eID = config.getBlock("Blocks", "Cigar Box (Filled)", 2090).getInt();
		dnafabricatorIdleID = config.getBlock("Blocks", "DNA Fabricator", 2091).getInt();
		dnafabricatorActiveID = config.getBlock("Blocks", "DNA Fabricator (Active)", 192).getInt();
		dnaextractorIdleID = config.getBlock("Blocks", "DNA Extractor", 2093).getInt();
		dnaextractorActiveID = config.getBlock("Blocks", "DNA Extractor (Active)", 2094).getInt();
		seedextractorIdleID = config.getBlock("Blocks", "Seed Extractor", 2095).getInt();
		seedextractorActiveID = config.getBlock("Blocks", "Seed Extractor (Active)", 2096).getInt();
		elementextractorIdleID = config.getBlock("Blocks", "Chemical Extractor", 2097).getInt();
		elementextractorActiveID = config.getBlock("Blocks", "Chemical Extractor (Active)", 2098).getInt();
		planksID = config.getBlock("Blocks", "Planks", 2099).getInt();



		strawberryCropID = config.getBlock("Plants", "Strawberry Crop", 2100).getInt();
		tomatoCropID = config.getBlock("Plants", "Tomato Crop", 2101).getInt();
		weedCropID = config.getBlock("Plants", "Cannabis Crop", 2102).getInt();
		lettuceCropID = config.getBlock("Plants", "Lettuce Crop", 2103).getInt();
		cornCropID = config.getBlock("Plants", "Corn Crop", 2104).getInt();
		pepperCropID = config.getBlock("Plants", "Pepper Crop", 2105).getInt();
		barleyCropID = config.getBlock("Plants", "Barley Crop", 2106).getInt();
		riceCropID = config.getBlock("Plants", "Rice Crop", 2107).getInt();
		cottonCropID = config.getBlock("Plants", "Cotton Crop", 2108).getInt();
		onionCropID = config.getBlock("Plants", "Onion Crop", 2109).getInt();
		oliveCropID = config.getBlock("Plants", "Olive Crop", 2110).getInt();
		lemonCropID = config.getBlock("Plants", "Lemon Crop", 2111).getInt();
		orangeCropID = config.getBlock("Plants", "Orange Crop", 2112).getInt();
		cherryCropID = config.getBlock("Plants", "Cherry Crop", 2113).getInt();
		lavenderCropID = config.getBlock("Plants", "Lavender Crop", 2114).getInt();
		parsleyCropID = config.getBlock("Plants", "Parsley Crop", 2115).getInt();
		tobaccoCropID = config.getBlock("Plants", "Tobacco Crop", 2116).getInt();
		peppersCropID = config.getBlock("Plants", "Bell Pepper Crop", 2117).getInt();
		walnutCropID = config.getBlock("Plants", "Walnut Crop", 2118).getInt();
		walnutHardCropID = config.getBlock("Plants", "Hard Walnut Crop", 2119).getInt();
		walnutHarderCropID = config.getBlock("Plants", "Iron Walnut Crop", 2120).getInt();
		walnutGoldCropID = config.getBlock("Plants", "Golden Walnut Crop", 2121).getInt();
		walnutDiamondCropID = config.getBlock("Plants", "Diamond Walnut Crop", 2122).getInt();
		grapeCropID = config.getBlock("Plants", "Grape Crop", 2123).getInt();
		grapeCropbID = config.getBlock("Plants", "Grape Crop (2)", 2124).getInt();
		grapeCropcID = config.getBlock("Plants", "Grape Crop (3)", 2125).getInt();
		grapeCropdID = config.getBlock("Plants", "Grape Crop (4)", 2126).getInt();
		garlicCropID = config.getBlock("Plants", "Garlic Crop", 2127).getInt();
		chicleCropID = config.getBlock("Plants", "Chicle Crop", 2128).getInt();
		peanutCropID = config.getBlock("Plants", "Peanut Crop", 2129).getInt();
		mintCropID = config.getBlock("Plants", "Mint Crop", 2130).getInt();
		truffleBlockID = config.getBlock("Plants", "Truffle Soil", 2131).getInt();
		truffleBlockWhiteID = config.getBlock("Plants", "White Truffle Soil", 2132).getInt();
		raspberryCropID = config.getBlock("Plants", "Raspberry Crop", 2133).getInt();
		braspberryCropID = config.getBlock("Plants", "Blue Raspberry Crop", 2134).getInt();
		blackcurrantCropID = config.getBlock("Plants", "Blackcurrant Crop", 2135).getInt();
		blueberryCropID = config.getBlock("Plants", "Blueberry Crop", 2136).getInt();
		hopsCropID = config.getBlock("Plants", "Hops Crop", 2137).getInt();
		grapePurpleCropID = config.getBlock("Plants", "Purple Grape Crop", 2138).getInt();
		grapePurpleCropbID = config.getBlock("Plants", "Purple Grape Crop (2)", 2139).getInt();
		grapePurpleCropcID = config.getBlock("Plants", "Purple Grape Crop (3)", 2140).getInt();
		grapePurpleCropdID = config.getBlock("Plants", "Purple Grape Crop (4)", 2141).getInt();

		roseCropID = config.getBlock("Plants", "Rose Crop", 2142).getInt();
		dandelionCropID = config.getBlock("Plants", "Dandelion Crop", 2143).getInt();

		lemonLogID = config.getBlock("Plants", "Lemon Log", 2144).getInt();
		lemonLeavesID = config.getBlock("Plants", "Lemon Leaves", 2145).getInt();
		lemonSaplingID = config.getBlock("Plants", "Lemon Sapling", 2146).getInt();

		orangeLogID = config.getBlock("Plants", "Orange Log", 2147).getInt();
		orangeLeavesID = config.getBlock("Plants", "Orange leaves", 2148).getInt();
		orangeSaplingID = config.getBlock("Plants", "Orange Sapling", 2149).getInt();

		cherryLogID = config.getBlock("Plants", "Cherry Log", 2150).getInt();
		cherryLeavesID = config.getBlock("Plants", "Cherry Leaves", 2151).getInt();
		cherrySaplingID = config.getBlock("Plants", "Cherry Sapling", 2152).getInt();

		oliveLogID = config.getBlock("Plants", "Olive Log", 2153).getInt();
		oliveLeavesID = config.getBlock("Plants", "Olive Leaves", 2154).getInt();
		oliveSaplingID = config.getBlock("Plants", "Olive Sapling", 2155).getInt();

		chicleLogID = config.getBlock("Plants", "Chicle Log", 2156).getInt();
		chicleLeavesID = config.getBlock("Plants", "Chicle Leaves", 2157).getInt();
		chicleSaplingID = config.getBlock("Plants", "Chicle Sapling", 2158).getInt();

		grass1ID = config.getBlock("Plants", "Hordeum", 2159).getInt();
		grass2ID = config.getBlock("Plants", "Gossipium", 2160).getInt();
		grass3ID = config.getBlock("Plants", "Solanum", 2161).getInt();
		wetClayID = config.getBlock("Plants", "Wet Clay", 2162).getInt();

		strawberryPlantID = config.getBlock("Plants", "Strawberry Plant", 2163).getInt();
		weedPlantID = config.getBlock("Plants", "Cannabis Plant", 2164).getInt();
		lettucePlantID = config.getBlock("Plants", "Lettuce Plant", 2165).getInt();
		cornPlantID = config.getBlock("Plants", "Corn Plant", 2166).getInt();
		pepperPlantID = config.getBlock("Plants", "Pepper Plant", 2167).getInt();
		onionPlantID = config.getBlock("Plants", "Onion Plant", 2168).getInt();
		parsleyPlantID = config.getBlock("Plants", "Parsley Plant", 2169).getInt();
		lavenderPlantID = config.getBlock("Plants", "Lavender Plant", 2170).getInt();
		tobaccoPlantID = config.getBlock("Plants", "Tobacco Plant", 2171).getInt();
		peppersPlantID = config.getBlock("Plants", "Bell Peppers Plant", 2172).getInt();
		walnutPlantID = config.getBlock("Plants", "Walnut Plant", 2173).getInt();
		seaweedID = config.getBlock("Plants", "Seaweed", 2174).getInt();



		DNAID = config.getItem("DNA", "Blank DNA", 5000).getInt();
		DNA1ID = config.getItem("DNA", "Rose DNA", 5001).getInt();
		DNA2ID = config.getItem("DNA", "Dandelion DNA", 5002).getInt();
		DNA3ID = config.getItem("DNA", "Strawberry DNA", 5003).getInt();
		DNA4ID = config.getItem("DNA", "Tomato DNA", 5004).getInt();
		DNA5ID = config.getItem("DNA", "Lemon DNA", 5005).getInt();
		DNA6ID = config.getItem("DNA", "Orange DNA", 5006).getInt();
		DNA7ID = config.getItem("DNA", "Cherry DNA", 5007).getInt();
		DNA8ID = config.getItem("DNA", "Lettuce DNA", 5008).getInt();
		DNA9ID = config.getItem("DNA", "Corn DNA", 5009).getInt();
		DNA10ID = config.getItem("DNA", "Pepper DNA", 5010).getInt();
		DNA11ID = config.getItem("DNA", "Rice DNA", 5011).getInt();
		DNA12ID = config.getItem("DNA", "Barley DNA", 5012).getInt();
		DNA13ID = config.getItem("DNA", "Cotton DNA", 5013).getInt();
		DNA14ID = config.getItem("DNA", "Onion DNA", 5014).getInt();
		DNA15ID = config.getItem("DNA", "Olive DNA", 5015).getInt();
		DNA16ID = config.getItem("DNA", "Cannabis DNA", 5016).getInt();
		DNA17ID = config.getItem("DNA", "Salty DNA", 5017).getInt();
		DNA18ID = config.getItem("DNA", "Sweet DNA", 5018).getInt();
		DNA19ID = config.getItem("DNA", "Bitter DNA", 5019).getInt();
		DNA20ID = config.getItem("DNA", "Sour DNA", 5020).getInt();
		DNA21ID = config.getItem("DNA", "Cocoa DNA", 5021).getInt();
		DNA22ID = config.getItem("DNA", "Apple DNA", 5022).getInt();
		DNA23ID = config.getItem("DNA", "Pumpkin DNA", 5023).getInt();
		DNA24ID = config.getItem("DNA", "Melon DNA", 5024).getInt();
		DNA25ID = config.getItem("DNA", "Wheat DNA", 5025).getInt();
		DNA26ID = config.getItem("DNA", "Sugar Cane DNA", 5026).getInt();
		DNA27ID = config.getItem("DNA", "Brown Mushroom DNA", 5027).getInt();
		DNA28ID = config.getItem("DNA", "Red Mushroom DNA", 5028).getInt();
		DNA29ID = config.getItem("DNA", "Carrot DNA", 5029).getInt();
		DNA30ID = config.getItem("DNA", "Potato DNA", 5030).getInt();
		DNA31ID = config.getItem("DNA", "Oak DNA", 5031).getInt();
		DNA32ID = config.getItem("DNA", "Spruce DNA", 5032).getInt();
		DNA33ID = config.getItem("DNA", "Birch DNA", 5033).getInt();
		DNA34ID = config.getItem("DNA", "Jungle DNA", 5034).getInt();
		DNA35ID = config.getItem("DNA", "Spiny DNA", 5035).getInt();
		DNA36ID = config.getItem("DNA", "Cactus DNA", 5036).getInt();
		DNA37ID = config.getItem("DNA", "Bean DNA", 5037).getInt();
		DNA38ID = config.getItem("DNA", "Root DNA", 5038).getInt();
		DNA39ID = config.getItem("DNA", "Leaf DNA", 5039).getInt();
		DNA40ID = config.getItem("DNA", "Lavender DNA", 5040).getInt();
		DNA41ID = config.getItem("DNA", "Parsley DNA", 5041).getInt();
		DNA42ID = config.getItem("DNA", "Herb DNA", 5042).getInt();
		DNA43ID = config.getItem("DNA", "Walnut DNA", 5043).getInt();
		DNA44ID = config.getItem("DNA", "Nutty DNA", 5044).getInt();
		DNA45ID = config.getItem("DNA", "Tobacco DNA", 5045).getInt();
		DNA46ID = config.getItem("DNA", "Bell Pepper DNA", 5046).getInt();
		DNA47ID = config.getItem("DNA", "Vine DNA", 5047).getInt();
		DNA48ID = config.getItem("DNA", "Gold (Au)", 5048).getInt();
		DNA49ID = config.getItem("DNA", "Iron (Fe)", 5049).getInt();
		DNA50ID = config.getItem("DNA", "Lazurite (Na3,Ca(Al3,Si3,O12)S)", 5050).getInt();
		DNA51ID = config.getItem("DNA", "Hardening DNA", 5051).getInt();
		DNA52ID = config.getItem("DNA", "Carbon (C)", 5052).getInt();
		DNA53ID = config.getItem("DNA", "Oxygen (O)", 5053).getInt();
		DNA54ID = config.getItem("DNA", "Enlarging DNA", 5054).getInt();
		DNA55ID = config.getItem("DNA", "Spicy DNA", 5055).getInt();
		DNA56ID = config.getItem("DNA", "Garlicy DNA", 5056).getInt();
		DNA57ID = config.getItem("DNA", "Garlic DNA", 5057).getInt();
		DNA58ID = config.getItem("DNA", "Grape DNA", 5058).getInt();
		DNA59ID = config.getItem("DNA", "Sticky DNA", 5059).getInt();
		DNA60ID = config.getItem("DNA", "Chicle DNA", 5060).getInt();
		DNA61ID = config.getItem("DNA", "Hard Nut DNA", 5061).getInt();
		DNA62ID = config.getItem("DNA", "Hardened Walnut DNA", 5062).getInt();
		DNA63ID = config.getItem("DNA", "Iron Walnut DNA", 5063).getInt();
		DNA64ID = config.getItem("DNA", "Peanut DNA", 5064).getInt();
		DNA65ID = config.getItem("DNA", "Caffeine (C8,H10,N4,O2)", 5065).getInt();
		DNA66ID = config.getItem("DNA", "Minty DNA", 5066).getInt();
		DNA67ID = config.getItem("DNA", "Mint DNA", 5067).getInt();
		DNA68ID = config.getItem("DNA", "Berry DNA", 5068).getInt();
		DNA69ID = config.getItem("DNA", "Raspberry DNA", 5069).getInt();
		DNA70ID = config.getItem("DNA", "Blue Raspberry DNA", 5070).getInt();
		DNA71ID = config.getItem("DNA", "Blackcurrant DNA", 5071).getInt();
		DNA72ID = config.getItem("DNA", "Blueberry DNA", 5072).getInt();
		DNA73ID = config.getItem("DNA", "Golden Walnut DNA", 5073).getInt();
		DNA74ID = config.getItem("DNA", "Diamond Walnut DNA", 5074).getInt();
		DNA75ID = config.getItem("DNA", "Hops DNA", 5075).getInt();
		DNA76ID = config.getItem("DNA", "Purple Grape DNA", 5076).getInt();
		DNA77ID = config.getItem("DNA", "Hydrogen (H)", 5077).getInt();
		DNA78ID = config.getItem("DNA", "Nitrogen (N)", 5078).getInt();



		cheesemoldID = config.getItem("Food", "Cheese Mold", 5079).getInt();
		cheesemoldFilledID = config.getItem("Food", "Filled Cheese Mold", 5080).getInt();
		cheesemoldSetID = config.getItem("Food", "Set Cheese Mold", 5081).getInt();

		strawID = config.getItem("Food", "Straw", 5082).getInt();
		stalkID = config.getItem("Food", "Stalk", 5083).getInt();
		wheatgrainID = config.getItem("Food", "Wheat Grain", 5084).getInt();
		barleygrainID = config.getItem("Food", "Barley Grain", 5085).getInt();
		barleymaltID = config.getItem("Food", "Malt Barley", 5086).getInt();
		flourID = config.getItem("Food", "Flour", 5087).getInt();
		doughID = config.getItem("Food", "Dough", 5088).getInt();
		pastaID = config.getItem("Food", "Pasta", 5089).getInt();
		pastryID = config.getItem("Food", "Pastry", 5090).getInt();
		doughbreadID = config.getItem("Food", "Bread Dough", 5091).getInt();
		magicyeastID = config.getItem("Food", "Enhancing Bacteria", 5092).getInt();
		yeastID = config.getItem("Food", "Yeast", 5093).getInt();
		cheesecurdID = config.getItem("Food", "Cheese Curds", 5094).getInt();
		lardID = config.getItem("Food", "Lard", 5095).getInt();
		butterID = config.getItem("Food", "Butter", 5096).getInt();
		creamID = config.getItem("Food", "Cream", 5097).getInt();
		caramelID = config.getItem("Food", "Caramel", 5098).getInt();
		cheeseID = config.getItem("Food", "Cheese", 5099).getInt();

		doughbiscuitID = config.getItem("Food", "Biscuit Dough", 5100).getInt();
		doughbiscuitchocolateID = config.getItem("Food", "Chocolate Biscuit Dough", 5101).getInt();
		doughbiscuitcaramelID = config.getItem("Food", "Caramel Biscuit Dough", 5102).getInt();
		doughbiscuitfruitID = config.getItem("Food", "Fruity Biscuit Dough", 5103).getInt();
		doughbiscuitpeanutbutterID = config.getItem("Food", "Peanut-Butter Biscuit Dough", 5104).getInt();
		biscuitID = config.getItem("Food", "Biscuit", 5105).getInt();
		biscuitchocolateID = config.getItem("Food", "Chcolate Biscuit", 5106).getInt();
		biscuitcaramelID = config.getItem("Food", "Caramel Biscuit", 5107).getInt();
		biscuitfruitID = config.getItem("Food", "Fruity Biscuit", 5108).getInt();
		biscuitcreamID = config.getItem("Food", "Cream-Filled Biscuit", 5109).getInt();
		biscuitjaffaID = config.getItem("Food", "Jaffa Cake", 5110).getInt();
		biscuitpeanutbutterID = config.getItem("Food", "Peanut Butter Biscuit", 5111).getInt();

		saltID = config.getItem("Food", "Salt", 5112).getInt();
		pepperID = config.getItem("Food", "Pepper", 5113).getInt();
		peppersaltID = config.getItem("Food", "Salt + Pepper Seasoning", 5114).getInt();

		bakedbreadID = config.getItem("Food", "Baked Bread", 5115).getInt();
		burntbreadID = config.getItem("Food", "Burnt Bread", 5116).getInt();
		buttieporkID = config.getItem("Food", "Pork Sandwich", 5117).getInt();
		buttiebeefID = config.getItem("Food", "Beef Sandwich", 5118).getInt();
		buttiefishID = config.getItem("Food", "Fish Sandwich", 5119).getInt();
		buttiesalamiID = config.getItem("Food", "Salami Sandwich", 5120).getInt();
		buttiecheeseID = config.getItem("Food", "Cheese Sandwich", 5121).getInt();
		buttiechickenID = config.getItem("Food", "Chicken Sandwich", 5122).getInt();
		buttielambID = config.getItem("Food", "Lamb Sandwich", 5123).getInt();
		buttiemammothID = config.getItem("Food", "Mammoth Meat Sandwich", 5124).getInt();
		buttiebaconID = config.getItem("Food", "Bacon Buttie", 5125).getInt();
		buttieeggID = config.getItem("Food", "Egg Sandwich", 5126).getInt();
		buttiejamID = config.getItem("Food", "Jam Sandwich", 5127).getInt();
		buttiemarmaladeID = config.getItem("Food", "Marmalade Sandwich", 5128).getInt();
		buttiepeanutbutterID = config.getItem("Food", "Peanut Butter Sandwich", 5129).getInt();
		buttiepbjID = config.getItem("Food", "Peanut Butter Jelly Sandwich", 5130).getInt();
		jamtoastID = config.getItem("Food", "Jam on Toast", 5131).getInt();
		jamorangetoastID = config.getItem("Food", "Marmalade on Toast", 5132).getInt();
		toastID = config.getItem("Food", "Toast", 5133).getInt();

		pizzacheeseID = config.getItem("Food", "Margarita Pizza", 5134).getInt();
		pizzacheesestuffedID = config.getItem("Food", "Margarita Pizza (Stuffed)", 5135).getInt();
		pepperonisliceID = config.getItem("Food", "Pepperoni Slice", 5136).getInt();
		cheesesliceID = config.getItem("Food", "Cheese Slice", 5137).getInt();
		breadsliceID = config.getItem("Food", "Bread Slice", 5138).getInt();
		pizzadoughID = config.getItem("Food", "Pizza Dough", 5139).getInt();
		pizzabaseID = config.getItem("Food", "Margarita Pizza Base", 5140).getInt();
		pizzadoughstuffedID = config.getItem("Food", "Pizza Dough (Stuffed)", 5141).getInt();
		pizzabasestuffedID = config.getItem("Food", "Margarita Pizza Base (Stuffed)", 5142).getInt();
		pizzapepperoniID = config.getItem("Food", "Pepperoni Pizza", 5143).getInt();
		pizzapepperonibaseID = config.getItem("Food", "Pepperoni Pizza Base", 5144).getInt();
		pizzapepperonistuffedID = config.getItem("Food", "Pepperoni Pizza (Stuffed)", 5145).getInt();
		pizzapepperonibasestuffedID = config.getItem("Food", "Pepperoni Pizza Base (Stuffed)", 5146).getInt();
		pizzacheesyID = config.getItem("Food", "Cheesy Pizza", 5147).getInt();
		pizzacheesybaseID = config.getItem("Food", "Cheesy Pizza Base", 5148).getInt();
		pizzacheesystuffedID = config.getItem("Food", "Cheesy Pizza (Stuffed)", 5149).getInt();
		pizzacheesybasestuffedID = config.getItem("Food", "Cheesy Pizza Base (Stuffed)", 5150).getInt();
		pizzameatID = config.getItem("Food", "Meaty Pizza", 5151).getInt();
		pizzameatbaseID = config.getItem("Food", "Meaty Pizza Base", 5152).getInt();
		pizzameatstuffedID = config.getItem("Food", "Meaty Pizza (Stuffed)", 5153).getInt();
		pizzameatbasestuffedID = config.getItem("Food", "Meaty Pizza Base (Stuffed)", 5154).getInt();
		pizzaamericaID = config.getItem("Food", "American-Style Pizza", 5155).getInt();
		pizzaamericabaseID = config.getItem("Food", "American-Style Pizza Base", 5156).getInt();
		pizzaamericastuffedID = config.getItem("Food", "American-Style Pizza (Stuffed)", 5157).getInt();
		pizzaamericabasestuffedID = config.getItem("Food", "American-Style Pizza Base (Stuffed)", 5158).getInt();
		pizzamushroomID = config.getItem("Food", "Mushroom Pizza", 5159).getInt();
		pizzamushroombaseID = config.getItem("Food", "Mushroom Pizza Base", 5160).getInt();
		pizzamushroomstuffedID = config.getItem("Food", "Mushroom Pizza (Stuffed)", 5161).getInt();
		pizzamushroombasestuffedID = config.getItem("Food", "Mushroom Pizza Base (Stuffed)", 5162).getInt();
		pizzavegID = config.getItem("Food", "Vegetarian Pizza", 5163).getInt();
		pizzavegbaseID = config.getItem("Food", "Vegetarian Pizza Base", 5164).getInt();
		pizzavegstuffedID = config.getItem("Food", "Vegetarian Pizza (Stuffed)", 5165).getInt();
		pizzavegbasestuffedID = config.getItem("Food", "Vegetarian Pizza Base (Stuffed)", 5166).getInt();
		gbreaddoughID = config.getItem("Food", "Garlic Bread Dough", 5167).getInt();
		gbreadID = config.getItem("Food", "Garlic Bread", 5168).getInt();

		baconRawID = config.getItem("Food", "Raw Bacon", 5169).getInt();
		baconCookedID = config.getItem("Food", "Fried Bacon", 5170).getInt();
		ribsID = config.getItem("Food", "Raw Ribs", 5171).getInt();
		ribsCookedID = config.getItem("Food", "Smoked Ribs", 5172).getInt();
		mammothmeatRawID = config.getItem("Food", "Raw Mammoth Meat", 5173).getInt();
		mammothmeatCookedID = config.getItem("Food", "Cooked Mammoth Meat", 5174).getInt();
		lambRawID = config.getItem("Food", "Raw Lambchop", 5175).getInt();
		lambCookedID = config.getItem("Food", "Cooked Lambchop", 5176).getInt();
		sausageID = config.getItem("Food", "Raw Sausage", 5177).getInt();
		sausageCookedID = config.getItem("Food", "Cooked Sausage", 5178).getInt();
		pepperoniID = config.getItem("Food", "Pepperoni", 5179).getInt();
		pigskinID = config.getItem("Food", "Pigskin", 5180).getInt();
		porkscratchingID = config.getItem("Food", "Pork Crackling", 5181).getInt();
		ribsCookedKID = config.getItem("Food", "Smoked Ribs (Seasoned)", 5182).getInt();
		lambCookedKID = config.getItem("Food", "Cooked Lambchop (Seasoned)", 5183).getInt();
		chickenCookedKID = config.getItem("Food", "Cooked Chicken (Seasoned)", 5184).getInt();
		porkCookedKID = config.getItem("Food", "Cooked Pork (Seasoned)", 5185).getInt();
		beefCookedKID = config.getItem("Food", "Cooked Steak (Seasoned)", 5186).getInt();
		fishCookedKID = config.getItem("Food", "Cooked Fish (Seasoned)", 5187).getInt();

		cheesewheelID = config.getItem("Food", "Cheese Wheel", 5188).getInt();
		eggFriedID = config.getItem("Food", "Fried Egg", 5189).getInt();
		eggScrambledID = config.getItem("Food", "Scrambled Egg", 5190).getInt();
		eggBoiledID = config.getItem("Food", "Boiled Egg", 5191).getInt();
		saladID = config.getItem("Food", "Salad", 5192).getInt();
		saladChickenID = config.getItem("Food", "Chicken Salad", 5193).getInt();
		saladEggID = config.getItem("Food", "Egg Salad", 5194).getInt();
		saladFruitID = config.getItem("Food", "Fruit Salad", 5195).getInt();
		seaweedDryID = config.getItem("Food", "Dried Seaweed", 5196).getInt();
		sushiID = config.getItem("Food", "Sushi", 5197).getInt();

		soupTomatoID = config.getItem("Food", "Tomato Soup", 5198).getInt();
		soupPumpkinID = config.getItem("Food", "Pumpkin Soup", 5199).getInt();
		soupChickenID = config.getItem("Food", "Chicken Soup", 5200).getInt();
		soupBeefID = config.getItem("Food", "Beef Stew", 5201).getInt();
		soupVegetableID = config.getItem("Food", "Vegetable Soup", 5202).getInt();
		soupCarrotID = config.getItem("Food", "Carrot Soup", 5203).getInt();

		potatoSliceID = config.getItem("Food", "Sliced Potato", 5204).getInt();
		potatoWedgeID = config.getItem("Food", "Raw Fries", 5205).getInt();
		crispsID = config.getItem("Food", "Crisps", 5206).getInt();
		chipsID = config.getItem("Food", "Fries", 5207).getInt();
		svchipsID = config.getItem("Food", "Salt + Vinegar Crisps", 5208).getInt();
		chippackID = config.getItem("Food", "Fries (Packaged)", 5209).getInt();
		friedfishID = config.getItem("Food", "Battered Fish", 5210).getInt();
		friedsausageID = config.getItem("Food", "Battered Sausage", 5211).getInt();
		friedspamID = config.getItem("Food", "Spam Fritter", 5212).getInt();
		fishcakeID = config.getItem("Food", "Raw Fish Cake", 5213).getInt();
		friedfishcakeID = config.getItem("Food", "Battered Fish Cake", 5214).getInt();
		friedchickenID = config.getItem("Food", "Fried Chicken", 5215).getInt();
		friedchickenpackID = config.getItem("Food", "Fried Chicken (Packaged)", 5216).getInt();
		bunID = config.getItem("Food", "Bread Bun", 5217).getInt();
		burgerRawID = config.getItem("Food", "Raw Burger", 5218).getInt();
		burgerCookedID = config.getItem("Food", "Cooked Burger", 5219).getInt();
		burgerRegularID = config.getItem("Food", "Regular Burger", 5220).getInt();
		burgerChickenID = config.getItem("Food", "Chicken Burger", 5221).getInt();
		burgerCheeseID = config.getItem("Food", "Cheese Burger", 5222).getInt();
		burgerBaconID = config.getItem("Food", "Bacon Burger", 5223).getInt();
		burgerBaconCheeseID = config.getItem("Food", "Bacon + Cheese Burger", 5224).getInt();
		burgerRegularKID = config.getItem("Food", "Regular Burger (Seasoned)", 5225).getInt();
		burgerChickenKID = config.getItem("Food", "Chicken Burger (Seasoned)", 5226).getInt();
		burgerCheeseKID = config.getItem("Food", "Cheese Burger (Seasoned)", 5227).getInt();
		burgerBaconKID = config.getItem("Food", "Bacon Burger (Seasoned)", 5228).getInt();
		burgerBaconCheeseKID = config.getItem("Food", "Bacon + Cheese Burger (Seasoned)", 5229).getInt();
		hotdogID = config.getItem("Food", "Hot Dog", 5230).getInt();
		hotdogketchupID = config.getItem("Food", "Hot Dog (Seasoned)", 5231).getInt();

		icecreamID = config.getItem("Food", "Ice Cream", 5232).getInt();
		cicecreamID = config.getItem("Food", "Chocolate Ice Cream", 5233).getInt();
		cookiedoughID = config.getItem("Food", "Cookie Dough", 5234).getInt();
		cdicecreamID = config.getItem("Food", "Cookie Dough Ice Cream", 5235).getInt();
		sicecreamID = config.getItem("Food", "Strawberry Ice Cream", 5236).getInt();
		blueberryicecreamID = config.getItem("Food", "Blueberry Ice Cream", 5237).getInt();
		blackcurranticecreamID = config.getItem("Food", "Blackcurrant Ice Cream", 5238).getInt();
		raspberryicecreamID = config.getItem("Food", "Raspberry Ice Cream", 5239).getInt();
		braspberryicecreamID = config.getItem("Food", "Blue Raspberry Ice Cream", 5240).getInt();
		micecreamID = config.getItem("Food", "Melon Ice Cream", 5241).getInt();
		licecreamID = config.getItem("Food", "Lemon Ice Cream", 5242).getInt();
		bubblegumicecreamID = config.getItem("Food", "Bubblegum Ice Cream", 5243).getInt();
		caramelicecreamID = config.getItem("Food", "Caramel Ice Cream", 5244).getInt();
		nuticecreamID = config.getItem("Food", "Nutty Ice Cream", 5245).getInt();
		chicecreamID = config.getItem("Food", "Cherry Ice Cream", 5246).getInt();
		minticecreamID = config.getItem("Food", "Mint Ice Cream", 5247).getInt();
		cminticecreamID = config.getItem("Food", "Mint-Choc-Chip Ice Cream", 5248).getInt();
		chocolateID = config.getItem("Food", "Chocolate", 5249).getInt();
		waferID = config.getItem("Food", "Candy Wafer", 5250).getInt();
		jellyID = config.getItem("Food", "Jelly", 5251).getInt();
		jellyAppleID = config.getItem("Food", "Jelly (Apple)", 5252).getInt();
		jellyStrawberryID = config.getItem("Food", "Jelly (Strawberry)", 5253).getInt();
		jellyLemonID = config.getItem("Food", "Jelly (Lemon)", 5254).getInt();
		jellyGrapeID = config.getItem("Food", "Jelly (Grape)", 5255).getInt();
		jellyCherryID = config.getItem("Food", "Jelly (Cherry)", 5256).getInt();
		jellyOrangeID = config.getItem("Food", "Jelly (Orange)", 5257).getInt();
		jellyBlackcurrantID = config.getItem("Food", "Jelly (Blackcurrant)", 5258).getInt();
		jellyRaspberryID = config.getItem("Food", "Jelly (Raspberry)", 5259).getInt();
		jellyBRaspberryID = config.getItem("Food", "Jelly (Blue Raspberry)", 5260).getInt();
		gumID = config.getItem("Food", "Bubblegum", 5261).getInt();
		gumAppleID = config.getItem("Food", "Bubblegum (Apple)", 5262).getInt();
		gumStrawberryID = config.getItem("Food", "Bubblegum (Strawberry)", 5263).getInt();
		gumLemonID = config.getItem("Food", "Bubblegum (Lemon)", 5264).getInt();
		gumGrapeID = config.getItem("Food", "Bubblegum (Grape)", 5265).getInt();
		gumCherryID = config.getItem("Food", "Bubblegum (Cherry)", 5266).getInt();
		gumOrangeID = config.getItem("Food", "Bubblegum (Orange)", 5267).getInt();
		gumMelonID = config.getItem("Food", "Bubblegum (Melon)", 5268).getInt();
		gumSweetID = config.getItem("Food", "Bubblegum (Sweet)", 5269).getInt();
		gumMintID = config.getItem("Food", "Bubblegum (Minty)", 5270).getInt();
		gumBlueberryID = config.getItem("Food", "Bubblegum (Blueberry)", 5271).getInt();
		gumBlackcurrantID = config.getItem("Food", "Bubblegum (Blackcurrant)", 5272).getInt();
		gumRaspberryID = config.getItem("Food", "Bubblegum (Raspberry)", 5273).getInt();
		gumBRaspberryID = config.getItem("Food", "Bubblegum (Blue Raspberry)", 5274).getInt();

		pieAppleID = config.getItem("Food", "Apple Pie", 5275).getInt();
		pieCherryID = config.getItem("Food", "Cherry Pie", 5276).getInt();
		pieBlueberryID = config.getItem("Food", "Blueberry Pie", 5277).getInt();
		pieCreamID = config.getItem("Food", "Cream Pie", 5278).getInt();
		pieChickenID = config.getItem("Food", "Chicken Pie", 5279).getInt();
		pieMeatID = config.getItem("Food", "Meat Pie", 5280).getInt();
		piePorkID = config.getItem("Food", "Pork Pie", 5281).getInt();
		pieShepherdsID = config.getItem("Food", "Shepherd's Pie", 5282).getInt();
		pieAppleCookedID = config.getItem("Food", "Apple Pie (Cooked)", 5283).getInt();
		pieCherryCookedID = config.getItem("Food", "Cherry Pie (Cooked)", 5284).getInt();
		pieCreamCookedID = config.getItem("Food", "Cream Pie (Cooked)", 5285).getInt();
		pieChickenCookedID = config.getItem("Food", "Chicken Pie (Cooked)", 5286).getInt();
		pieMeatCookedID = config.getItem("Food", "Meat Pie (Cooked)", 5287).getInt();
		piePorkCookedID = config.getItem("Food", "Pork Pie (Cooked)", 5288).getInt();
		pieShepherdsCookedID = config.getItem("Food", "Shepherd's Pie (Cooked)", 5289).getInt();
		pieBlueberryCookedID = config.getItem("Food", "Blueberry Pie (Cooked)", 5290).getInt();

		packID = config.getItem("Food", "Packaging", 5291).getInt();
		cornoncobID = config.getItem("Food", "Corn on the Cob", 5292).getInt();
		popcornID = config.getItem("Food", "Popcorn", 5293).getInt();
		popcornpackID = config.getItem("Food", "Popcorn (Packaged)", 5294).getInt();
		toffeeappleID = config.getItem("Food", "Toffee Apple", 5295).getInt();

		vinegarID = config.getItem("Food", "Vinegar", 5296).getInt();
		jamID = config.getItem("Food", "Strawberry Jam", 5297).getInt();
		jamOrangeID = config.getItem("Food", "Marmalade", 5298).getInt();
		peanutbutterID = config.getItem("Food", "Peanut Butter", 5299).getInt();
		treacleID = config.getItem("Food", "Treacle", 5300).getInt();
		custardID = config.getItem("Food", "Custard", 5301).getInt();
		ketchupID = config.getItem("Food", "Tomato Ketchup", 5302).getInt();
		bbqID = config.getItem("Food", "BBQ Sauce", 5303).getInt();
		mayoID = config.getItem("Food", "Mayonaise", 5304).getInt();
		garlicsauceID = config.getItem("Food", "Garlic Sauce", 5305).getInt();
		gravyID = config.getItem("Food", "Gravy", 5306).getInt();
		saladcreamID = config.getItem("Food", "Salad Cream", 5307).getInt();
		mintsauceID = config.getItem("Food", "Mint Sauce", 5308).getInt();
		orangejuiceID = config.getItem("Food", "Orange Juice", 5309).getInt();
		applejuiceID = config.getItem("Food", "Apple Juice", 5310).getInt();
		lemonjuiceID = config.getItem("Food", "Lemon Juice", 5311).getInt();
		grapejuiceID = config.getItem("Food", "Grape Juice", 5312).getInt();
		melonjuiceID = config.getItem("Food", "Melon Juice", 5313).getInt();
		cherryjuiceID = config.getItem("Food", "Cherry Juice", 5314).getInt();
		blackcurrantjuiceID = config.getItem("Food", "Blackcurrant Juice", 5315).getInt();
		blueberryjuiceID = config.getItem("Food", "Blueberry Juice", 5316).getInt();
		raspberryjuiceID = config.getItem("Food", "Raspberry Juice", 5317).getInt();
		braspberryjuiceID = config.getItem("Food", "Blue Raspberry Juice", 5318).getInt();
		strawberryjuiceID = config.getItem("Food", "Strawberry Juice", 5319).getInt();
		lemonadeID = config.getItem("Food", "Lemonade", 5320).getInt();
		cherryadeID = config.getItem("Food", "Cherryade", 5321).getInt();
		orangeadeID = config.getItem("Food", "Orangeade", 5322).getInt();
		appleadeID = config.getItem("Food", "Appleade", 5323).getInt();
		blackcurrantadeID = config.getItem("Food", "Blackcurrantade", 5324).getInt();
		hotchocolatemilkID = config.getItem("Food", "Hot Chocolate", 5325).getInt();
		chocolatemilkID = config.getItem("Food", "Chocolate Milk", 5326).getInt();

		beerbasicBucketID = config.getItem("Food", "Bucket of Beer", 5327).getInt();
		beerbasicID = config.getItem("Food", "Beer", 5328).getInt();
		beerstrongBucketID = config.getItem("Food", "Bucket of Beer (Strong)", 5329).getInt();
		beerstrongID = config.getItem("Food", "Beer (Strong)", 5330).getInt();
		aleBucketID = config.getItem("Food", "Bucket of Ale", 5331).getInt();
		aleID = config.getItem("Food", "Ale", 5332).getInt();
		alestrongBucketID = config.getItem("Food", "Bucket of Ale (Strong)", 5333).getInt();
		alestrongID = config.getItem("Food", "Ale (Strong)", 5334).getInt();
		ciderBucketID = config.getItem("Food", "Bucket of Cider", 5335).getInt();
		ciderID = config.getItem("Food", "Cider", 5336).getInt();
		ciderstrongBucketID = config.getItem("Food", "Bucket of Cider (Strong)", 5337).getInt();
		ciderstrongID = config.getItem("Food", "Cider (Strong)", 5338).getInt();
		eggnogBucketID = config.getItem("Food", "Bucket of Eggnog", 5339).getInt();
		eggnogID = config.getItem("Food", "Eggnog", 5340).getInt();

		winebasicBucketID = config.getItem("Food", "Bucket of Wine", 5341).getInt();
		winebasicID = config.getItem("Food", "Wine", 5342).getInt();
		winestrongBucketID = config.getItem("Food", "Bucket of Wine (Strong)", 5343).getInt();
		winestrongID = config.getItem("Food", "Wine (Strong)", 5344).getInt();
		winewhiteBucketID = config.getItem("Food", "Bucket of White Wine", 5345).getInt();
		winewhiteID = config.getItem("Food", "White Wine", 5346).getInt();
		winewhitestrongBucketID = config.getItem("Food", "Bucket of White Wine (Strong)", 5347).getInt();
		winewhitestrongID = config.getItem("Food", "White Wine (Strong)", 5348).getInt();
		wineredBucketID = config.getItem("Food", "Bucket of Red Wine", 5349).getInt();
		wineredID = config.getItem("Food", "Red Wine", 5350).getInt();
		wineredstrongBucketID = config.getItem("Food", "Bucket of Red Wine (Strong)", 5351).getInt();
		wineredstrongID = config.getItem("Food", "Red Wine (Strong)", 5352).getInt();

		vodkabasicBucketID = config.getItem("Food", "Bucket of Vodka", 5353).getInt();
		vodkabasicID = config.getItem("Food", "Vodka", 5354).getInt();

		goldcookieID = config.getItem("Food", "Golden Cookie", 5355).getInt();
		co2ID = config.getItem("Food", "Carbonated Water", 5356).getInt();
		bottleAirID = config.getItem("Food", "Bottled Air", 5357).getInt();

		cupID = config.getItem("Food", "Drinking Glass", 5358).getInt();
		jarID = config.getItem("Food", "Jar", 5359).getInt();
		mugID = config.getItem("Food", "Stone Mug", 5360).getInt();
		winecupID = config.getItem("Food", "Wine Glass", 5361).getInt();
		tankardID = config.getItem("Food", "Beer Glass", 5362).getInt();



		organicfuelBlockID = config.getBlock("Fuels", "Organic Coal Block", 3000).getInt();
		organicfuelBlock2ID = config.getBlock("Fuels", "Organismal Coal Block", 3001).getInt();
		organicfuelBlock3ID = config.getBlock("Fuels", "Biotic Coal Block", 3002).getInt();
		firefuelBlockID = config.getBlock("Fuels", "Fiery Coal Block", 3003).getInt();
		firefuelBlock2ID = config.getBlock("Fuels", "Blazing Coal Block", 3004).getInt();
		firefuelBlock3ID = config.getBlock("Fuels", "Inferno Coal Block", 3005).getInt();
		organicfuelID = config.getItem("Fuels", "Organic Coal", 5363).getInt();
		organicfuel2ID = config.getItem("Fuels", "Organismal Coal", 5364).getInt();
		organicfuel3ID = config.getItem("Fuels", "Biotic Coal", 5365).getInt();
		firefuelID = config.getItem("Fuels", "Fiery Coal", 5366).getInt();
		firefuel2ID = config.getItem("Fuels", "Blazing Coal", 5367).getInt();
		firefuel3ID = config.getItem("Fuels", "Inferno Coal", 5368).getInt();

		config.save();
	}

	@Init
	public void load (FMLInitializationEvent event)
	{

	}

	@PostInit
	public void postInit(FMLPostInitializationEvent event)
	{
		// this is the post initialization.
	}
}