// Date: 20/02/2014 16:35:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer Base1;
    ModelRenderer Base2;
    ModelRenderer Tower;
    ModelRenderer GlassFront;
    ModelRenderer Top1;
    ModelRenderer Top2;
    ModelRenderer Bottom;
    ModelRenderer GlassBack;
    ModelRenderer GlassRight;
    ModelRenderer GlassLeft;
    ModelRenderer Inside;
  
  public ModelModel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Base1 = new ModelRenderer(this, 0, 0);
      Base1.addBox(0F, 0F, 0F, 20, 2, 20);
      Base1.setRotationPoint(-10F, 22F, -10F);
      Base1.setTextureSize(64, 32);
      Base1.mirror = true;
      setRotation(Base1, 0F, 0F, 0F);
      Base2 = new ModelRenderer(this, 0, 0);
      Base2.addBox(0F, 0F, 0F, 16, 2, 16);
      Base2.setRotationPoint(-8F, 20F, -8F);
      Base2.setTextureSize(64, 32);
      Base2.mirror = true;
      setRotation(Base2, 0F, 0F, 0F);
      Tower = new ModelRenderer(this, 0, 0);
      Tower.addBox(0F, 0F, 0F, 8, 24, 8);
      Tower.setRotationPoint(-4F, -4F, -4F);
      Tower.setTextureSize(64, 32);
      Tower.mirror = true;
      setRotation(Tower, 0F, 0F, 0F);
      GlassFront = new ModelRenderer(this, 0, 40);
      GlassFront.addBox(0F, 0F, 0F, 12, 10, 1);
      GlassFront.setRotationPoint(-6F, -16F, -6F);
      GlassFront.setTextureSize(64, 32);
      GlassFront.mirror = true;
      setRotation(GlassFront, 0F, 0F, 0F);
      Top1 = new ModelRenderer(this, 0, 0);
      Top1.addBox(0F, 0F, 0F, 14, 2, 14);
      Top1.setRotationPoint(-7F, -18F, -7F);
      Top1.setTextureSize(64, 32);
      Top1.mirror = true;
      setRotation(Top1, 0F, 0F, 0F);
      Top2 = new ModelRenderer(this, 0, 0);
      Top2.addBox(0F, 0F, 0F, 10, 2, 10);
      Top2.setRotationPoint(-5F, -20F, -5F);
      Top2.setTextureSize(64, 32);
      Top2.mirror = true;
      setRotation(Top2, 0F, 0F, 0F);
      Bottom = new ModelRenderer(this, 0, 0);
      Bottom.addBox(0F, 0F, 0F, 14, 2, 14);
      Bottom.setRotationPoint(-7F, -6F, -7F);
      Bottom.setTextureSize(64, 32);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
      GlassBack = new ModelRenderer(this, 0, 40);
      GlassBack.addBox(0F, 0F, 0F, 12, 10, 1);
      GlassBack.setRotationPoint(-6F, -16F, 5F);
      GlassBack.setTextureSize(64, 32);
      GlassBack.mirror = true;
      setRotation(GlassBack, 0F, 0F, 0F);
      GlassRight = new ModelRenderer(this, 0, 40);
      GlassRight.addBox(0F, 0F, 0F, 10, 10, 1);
      GlassRight.setRotationPoint(-6F, -16F, 5F);
      GlassRight.setTextureSize(64, 32);
      GlassRight.mirror = true;
      setRotation(GlassRight, 0F, 1.570796F, 0F);
      GlassLeft = new ModelRenderer(this, 0, 40);
      GlassLeft.addBox(0F, 0F, 0F, 10, 10, 1);
      GlassLeft.setRotationPoint(5F, -16F, 5F);
      GlassLeft.setTextureSize(64, 32);
      GlassLeft.mirror = true;
      setRotation(GlassLeft, 0F, 1.570796F, 0F);
      Inside = new ModelRenderer(this, 0, 107);
      Inside.addBox(0F, 0F, 0F, 10, 10, 10);
      Inside.setRotationPoint(-5F, -16F, -5F);
      Inside.setTextureSize(64, 32);
      Inside.mirror = true;
      setRotation(Inside, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Base1.render(f5);
    Base2.render(f5);
    Tower.render(f5);
    GlassFront.render(f5);
    Top1.render(f5);
    Top2.render(f5);
    Bottom.render(f5);
    GlassBack.render(f5);
    GlassRight.render(f5);
    GlassLeft.render(f5);
    Inside.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
