// Date: 03/02/2013 14:11:15
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package agentsmod;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelMammoth extends ModelBase
{
  //fields
    ModelRenderer FRightLeg1;
    ModelRenderer FLeftLeg1;
    ModelRenderer BLeftLeg1;
    ModelRenderer BRightLeg1;
    ModelRenderer Body1;
    ModelRenderer Body2;
    ModelRenderer Body3;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Body4;
    ModelRenderer Body5;
    ModelRenderer Head2;
    ModelRenderer Head1;
    ModelRenderer Head3;
    ModelRenderer Trunk1;
    ModelRenderer Trunk2;
    ModelRenderer Trunk3;
    ModelRenderer Tusk1;
    ModelRenderer Tusk2;
    ModelRenderer Tusk1b;
    ModelRenderer Tusk2b;
    ModelRenderer Tusk2c;
    ModelRenderer Tusk1c;
    ModelRenderer Tusk1d;
    ModelRenderer Tusk2d;
    
    protected float field_78145_g = 8.0F;
    protected float field_78151_h = 4.0F;
  
  public ModelMammoth()
  {
    textureWidth = 512;
    textureHeight = 512;
    
    FRightLeg1 = new ModelRenderer(this, 0, 0);
    FRightLeg1.addBox(-12F, 0F, -12F, 12, 36, 12);
    FRightLeg1.setRotationPoint(-8F, -12F, -9F);
    FRightLeg1.setTextureSize(512, 512);
    FRightLeg1.mirror = true;
    setRotation(FRightLeg1, 0F, 0F, 0F);
    FLeftLeg1 = new ModelRenderer(this, 0, 0);
    FLeftLeg1.addBox(0F, 0F, -13F, 12, 36, 12);
    FLeftLeg1.setRotationPoint(8F, -12F, -8F);
    FLeftLeg1.setTextureSize(512, 512);
    FLeftLeg1.mirror = true;
    setRotation(FLeftLeg1, 0F, 0F, 0F);
    BLeftLeg1 = new ModelRenderer(this, 0, 0);
    BLeftLeg1.addBox(0F, 0F, 0F, 12, 36, 12);
    BLeftLeg1.setRotationPoint(8F, -12F, 26F);
    BLeftLeg1.setTextureSize(512, 512);
    BLeftLeg1.mirror = true;
    setRotation(BLeftLeg1, 0F, 0F, 0F);
    BRightLeg1 = new ModelRenderer(this, 0, 0);
    BRightLeg1.addBox(-12F, 0F, 0F, 12, 36, 12);
    BRightLeg1.setRotationPoint(-8F, -12F, 26F);
    BRightLeg1.setTextureSize(512, 512);
    BRightLeg1.mirror = true;
    setRotation(BRightLeg1, 0F, 0F, 0F);
    Body1 = new ModelRenderer(this, 0, 110);
    Body1.addBox(0F, 0F, -4F, 40, 31, 56);
    Body1.setRotationPoint(-20F, -44F, -15F);
    Body1.setTextureSize(512, 512);
    Body1.mirror = true;
    setRotation(Body1, -0.1396263F, 0F, 0F);
    Body1.mirror = true;
    Body2 = new ModelRenderer(this, 0, 0);
    Body2.addBox(0F, 0F, -1F, 40, 16, 65);
    Body2.setRotationPoint(-20F, -20F, -21F);
    Body2.setTextureSize(512, 512);
    Body2.mirror = true;
    setRotation(Body2, -0.0174533F, 0F, 0F);
    Body3 = new ModelRenderer(this, 0, 0);
    Body3.addBox(0F, 0F, 0F, 40, 8, 19);
    Body3.setRotationPoint(-20F, -36F, 38F);
    Body3.setTextureSize(512, 512);
    Body3.mirror = true;
    setRotation(Body3, -1.377414F, 0F, 0F);
    Tail1 = new ModelRenderer(this, 0, 0);
    Tail1.addBox(0F, 0F, 0F, 4, 16, 4);
    Tail1.setRotationPoint(-2F, -24F, 41F);
    Tail1.setTextureSize(512, 512);
    Tail1.mirror = true;
    setRotation(Tail1, 0.1487195F, 0F, 0F);
    Tail2 = new ModelRenderer(this, 0, 0);
    Tail2.addBox(0F, 0F, 0F, 3, 16, 3);
    Tail2.setRotationPoint(-1.5F, -9F, 44.4F);
    Tail2.setTextureSize(512, 512);
    Tail2.mirror = true;
    setRotation(Tail2, 0.37179F, 0F, 0F);
    Tail3 = new ModelRenderer(this, 0, 497);
    Tail3.addBox(0F, 0F, 0F, 2, 12, 2);
    Tail3.setRotationPoint(-1F, 5F, 50.4F);
    Tail3.setTextureSize(512, 512);
    Tail3.mirror = true;
    setRotation(Tail3, 0.7063871F, 0F, 0F);
    Body4 = new ModelRenderer(this, 0, 0);
    Body4.addBox(0F, 0F, 0F, 38, 24, 9);
    Body4.setRotationPoint(-19F, -44F, -18.9F);
    Body4.setTextureSize(512, 512);
    Body4.mirror = true;
    setRotation(Body4, -0.4833166F, 0F, 0F);
    Body5 = new ModelRenderer(this, 0, 0);
    Body5.addBox(0F, 0F, 0F, 36, 20, 6);
    Body5.setRotationPoint(-18F, -23F, -30F);
    Body5.setTextureSize(512, 512);
    Body5.mirror = true;
    setRotation(Body5, 0.37179F, 0F, 0F);
    Head2 = new ModelRenderer(this, 0, 0);
    Head2.addBox(0F, 0F, 0F, 24, 26, 20);
    Head2.setRotationPoint(-12F, -38F, -40.5F);
    Head2.setTextureSize(512, 512);
    Head2.mirror = true;
    setRotation(Head2, 0.1487195F, 0F, 0F);
    Head1 = new ModelRenderer(this, 0, 0);
    Head1.addBox(0F, 0F, 0F, 18, 6, 16);
    Head1.setRotationPoint(-9F, -43F, -39F);
    Head1.setTextureSize(512, 512);
    Head1.mirror = true;
    setRotation(Head1, 0.1487195F, 0F, 0F);
    Head3 = new ModelRenderer(this, 453, 463);
    Head3.addBox(0F, 0F, 0F, 20, 24, 5);
    Head3.setRotationPoint(-10F, -36F, -41F);
    Head3.setTextureSize(512, 512);
    Head3.mirror = true;
    setRotation(Head3, -0.0083601F, 0F, 0F);
    Trunk1 = new ModelRenderer(this, 0, 0);
    Trunk1.addBox(0F, 0F, 0F, 10, 16, 7);
    Trunk1.setRotationPoint(-5F, -15F, -41.5F);
    Trunk1.setTextureSize(512, 512);
    Trunk1.mirror = true;
    setRotation(Trunk1, -0.2047097F, 0F, 0F);
    Trunk2 = new ModelRenderer(this, 0, 0);
    Trunk2.addBox(0F, 0F, 0F, 8, 14, 5);
    Trunk2.setRotationPoint(-4F, -2F, -44F);
    Trunk2.setTextureSize(512, 512);
    Trunk2.mirror = true;
    setRotation(Trunk2, -0.7544884F, 0F, 0F);
    Trunk3 = new ModelRenderer(this, 0, 0);
    Trunk3.addBox(0F, 0F, 0F, 6, 12, 4);
    Trunk3.setRotationPoint(-3F, 7F, -51F);
    Trunk3.setTextureSize(512, 512);
    Trunk3.mirror = true;
    setRotation(Trunk3, -1.264997F, 0F, 0F);
    Tusk1 = new ModelRenderer(this, 0, 450);
    Tusk1.addBox(0F, 0F, 0F, 3, 16, 3);
    Tusk1.setRotationPoint(6F, -13F, -37F);
    Tusk1.setTextureSize(512, 512);
    Tusk1.mirror = true;
    setRotation(Tusk1, -0.2443461F, 0F, -0.2617994F);
    Tusk2 = new ModelRenderer(this, 0, 450);
    Tusk2.addBox(0F, 0F, 0F, 3, 16, 3);
    Tusk2.setRotationPoint(-9F, -14F, -39F);
    Tusk2.setTextureSize(512, 512);
    Tusk2.mirror = true;
    setRotation(Tusk2, -0.2443461F, 0F, 0.2617994F);
    Tusk1b = new ModelRenderer(this, 0, 450);
    Tusk1b.addBox(0F, 0F, 0F, 3, 11, 3);
    Tusk1b.setRotationPoint(9F, 1F, -40F);
    Tusk1b.setTextureSize(512, 512);
    Tusk1b.mirror = true;
    setRotation(Tusk1b, -0.7330383F, 0F, -0.7853982F);
    Tusk2b = new ModelRenderer(this, 0, 450);
    Tusk2b.addBox(0F, 0F, 0F, 3, 11, 3);
    Tusk2b.setRotationPoint(-11F, -2F, -42F);
    Tusk2b.setTextureSize(512, 512);
    Tusk2b.mirror = true;
    setRotation(Tusk2b, -0.7330383F, 0F, 0.7853982F);
    Tusk2c = new ModelRenderer(this, 0, 450);
    Tusk2c.addBox(0F, 0F, 0F, 3, 11, 3);
    Tusk2c.setRotationPoint(-14F, 4.466667F, -48F);
    Tusk2c.setTextureSize(512, 512);
    Tusk2c.mirror = true;
    setRotation(Tusk2c, -0.6981317F, 0F, 2.094395F);
    Tusk1c = new ModelRenderer(this, 0, 450);
    Tusk1c.addBox(0F, 0F, 0F, 3, 11, 3);
    Tusk1c.setRotationPoint(15F, 8F, -46F);
    Tusk1c.setTextureSize(512, 512);
    Tusk1c.mirror = true;
    setRotation(Tusk1c, -0.6981317F, 0F, -2.094395F);
    Tusk1d = new ModelRenderer(this, 0, 450);
    Tusk1d.addBox(0F, 0F, 0F, 3, 16, 3);
    Tusk1d.setRotationPoint(23F, 4F, -53F);
    Tusk1d.setTextureSize(512, 512);
    Tusk1d.mirror = true;
    setRotation(Tusk1d, -0.3490659F, 0F, -2.96706F);
    Tusk2d = new ModelRenderer(this, 0, 450);
    Tusk2d.addBox(0F, 0F, 0F, 3, 16, 3);
    Tusk2d.setRotationPoint(-21F, 3F, -55F);
    Tusk2d.setTextureSize(512, 512);
    Tusk2d.mirror = true;
    setRotation(Tusk2d, -0.3490659F, 0F, 2.96706F);

      
      --this.FRightLeg1.rotationPointX;
      ++this.FLeftLeg1.rotationPointX;
      this.FRightLeg1.rotationPointZ += 0.0F;
      this.FLeftLeg1.rotationPointZ += 0.0F;
      --this.BRightLeg1.rotationPointX;
      ++this.BLeftLeg1.rotationPointX;
      --this.BRightLeg1.rotationPointZ;
      --this.BLeftLeg1.rotationPointZ;
      this.field_78151_h += 2.0F;
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7){
	  super.render(par1Entity, par2, par3, par4, par5, par6, par7);
	  setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    FRightLeg1.render(par7);
    FLeftLeg1.render(par7);
    BLeftLeg1.render(par7);
    BRightLeg1.render(par7);
    Body1.render(par7);
    Body2.render(par7);
    Body3.render(par7);
    Tail1.render(par7);
    Tail2.render(par7);
    Tail3.render(par7);
    Body4.render(par7);
    Body5.render(par7);
    Head2.render(par7);
    Head1.render(par7);
    Head3.render(par7);
    Trunk1.render(par7);
    Trunk2.render(par7);
    Trunk3.render(par7);
    Tusk1.render(par7);
    Tusk2.render(par7);
    Tusk1b.render(par7);
    Tusk2b.render(par7);
    Tusk2c.render(par7);
    Tusk1c.render(par7);
    Tusk1d.render(par7);
    Tusk2d.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
    
    /*/
    this.Head1.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Head1.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Head2.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Head2.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Head3.rotateAngleX = par5 / (180F / (float)Math.PI);
    this.Head3.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.Body1.rotateAngleX = ((float)Math.PI / 2F);
    this.Body2.rotateAngleX = ((float)Math.PI / 2F);
    this.Body3.rotateAngleX = ((float)Math.PI / 2F);
    this.Body4.rotateAngleX = ((float)Math.PI / 2F);
    this.Body5.rotateAngleX = ((float)Math.PI / 2F);
    /*/
    
    this.FRightLeg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.4F * par2;
    this.FLeftLeg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.4F * par2;
    this.BRightLeg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.4F * par2;
    this.BLeftLeg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.4F * par2;

  }

}
