// Date: 20/02/2014 12:52:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Circle1;
    ModelRenderer Circle2;
    ModelRenderer Circle3;
    ModelRenderer Circle4;
    ModelRenderer Point1;
    ModelRenderer Point2;
    ModelRenderer Point4;
    ModelRenderer Point5;
    ModelRenderer Point7;
    ModelRenderer Point8;
    ModelRenderer Point10;
    ModelRenderer Point11;
    ModelRenderer Inside1;
    ModelRenderer Inside2;
    ModelRenderer Inside3;
    ModelRenderer Inside4;
  
  public ModelModel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 32, 6, 32);
      Base.setRotationPoint(-16F, 18F, -16F);
      Base.setTextureSize(128, 128);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Circle1 = new ModelRenderer(this, 76, 48);
      Circle1.addBox(0F, 0F, 0F, 6, 4, 20);
      Circle1.setRotationPoint(-10F, 14F, -10F);
      Circle1.setTextureSize(128, 128);
      Circle1.mirror = true;
      setRotation(Circle1, 0F, 0F, 0F);
      Circle2 = new ModelRenderer(this, 76, 48);
      Circle2.addBox(0F, 0F, 0F, 6, 4, 20);
      Circle2.setRotationPoint(4F, 14F, -10F);
      Circle2.setTextureSize(128, 128);
      Circle2.mirror = true;
      setRotation(Circle2, 0F, 0F, 0F);
      Circle3 = new ModelRenderer(this, 76, 76);
      Circle3.addBox(0F, 0F, 0F, 8, 4, 6);
      Circle3.setRotationPoint(-4F, 14F, -10F);
      Circle3.setTextureSize(128, 128);
      Circle3.mirror = true;
      setRotation(Circle3, 0F, 0F, 0F);
      Circle4 = new ModelRenderer(this, 76, 76);
      Circle4.addBox(0F, 0F, 0F, 8, 4, 6);
      Circle4.setRotationPoint(-4F, 14F, 4F);
      Circle4.setTextureSize(128, 128);
      Circle4.mirror = true;
      setRotation(Circle4, 0F, 0F, 0F);
      Point1 = new ModelRenderer(this, 0, 48);
      Point1.addBox(0F, 0F, 0F, 2, 4, 16);
      Point1.setRotationPoint(10F, 14F, -8F);
      Point1.setTextureSize(128, 128);
      Point1.mirror = true;
      setRotation(Point1, 0F, 0F, 0F);
      Point2 = new ModelRenderer(this, 0, 48);
      Point2.addBox(0F, 0F, 0F, 2, 4, 8);
      Point2.setRotationPoint(12F, 14F, -4F);
      Point2.setTextureSize(128, 128);
      Point2.mirror = true;
      setRotation(Point2, 0F, 0F, 0F);
      Point4 = new ModelRenderer(this, 0, 48);
      Point4.addBox(0F, 0F, 0F, 16, 4, 2);
      Point4.setRotationPoint(-8F, 14F, -12F);
      Point4.setTextureSize(128, 128);
      Point4.mirror = true;
      setRotation(Point4, 0F, 0F, 0F);
      Point5 = new ModelRenderer(this, 0, 48);
      Point5.addBox(0F, 0F, 0F, 8, 4, 2);
      Point5.setRotationPoint(-4F, 14F, -14F);
      Point5.setTextureSize(128, 128);
      Point5.mirror = true;
      setRotation(Point5, 0F, 0F, 0F);
      Point7 = new ModelRenderer(this, 0, 48);
      Point7.addBox(0F, 0F, 0F, 2, 4, 16);
      Point7.setRotationPoint(-12F, 14F, -8F);
      Point7.setTextureSize(128, 128);
      Point7.mirror = true;
      setRotation(Point7, 0F, 0F, 0F);
      Point8 = new ModelRenderer(this, 0, 48);
      Point8.addBox(0F, 0F, 0F, 2, 4, 8);
      Point8.setRotationPoint(-14F, 14F, -4F);
      Point8.setTextureSize(128, 128);
      Point8.mirror = true;
      setRotation(Point8, 0F, 0F, 0F);
      Point10 = new ModelRenderer(this, 0, 48);
      Point10.addBox(0F, 0F, 0F, 16, 4, 2);
      Point10.setRotationPoint(-8F, 14F, 10F);
      Point10.setTextureSize(128, 128);
      Point10.mirror = true;
      setRotation(Point10, 0F, 0F, 0F);
      Point11 = new ModelRenderer(this, 0, 48);
      Point11.addBox(0F, 0F, 0F, 8, 4, 2);
      Point11.setRotationPoint(-4F, 14F, 12F);
      Point11.setTextureSize(128, 128);
      Point11.mirror = true;
      setRotation(Point11, 0F, 0F, 0F);
      Inside1 = new ModelRenderer(this, 0, 0);
      Inside1.addBox(0F, 0F, 0F, 2, 4, 2);
      Inside1.setRotationPoint(-4F, 14F, -4F);
      Inside1.setTextureSize(128, 128);
      Inside1.mirror = true;
      setRotation(Inside1, 0F, 0F, 0F);
      Inside2 = new ModelRenderer(this, 0, 0);
      Inside2.addBox(0F, 0F, 0F, 2, 4, 2);
      Inside2.setRotationPoint(-4F, 14F, 2F);
      Inside2.setTextureSize(128, 128);
      Inside2.mirror = true;
      setRotation(Inside2, 0F, 0F, 0F);
      Inside3 = new ModelRenderer(this, 0, 0);
      Inside3.addBox(0F, 0F, 0F, 2, 4, 2);
      Inside3.setRotationPoint(2F, 14F, -4F);
      Inside3.setTextureSize(128, 128);
      Inside3.mirror = true;
      setRotation(Inside3, 0F, 0F, 0F);
      Inside4 = new ModelRenderer(this, 0, 0);
      Inside4.addBox(0F, 0F, 0F, 2, 4, 2);
      Inside4.setRotationPoint(2F, 14F, 2F);
      Inside4.setTextureSize(128, 128);
      Inside4.mirror = true;
      setRotation(Inside4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Base.render(f5);
    Circle1.render(f5);
    Circle2.render(f5);
    Circle3.render(f5);
    Circle4.render(f5);
    Point1.render(f5);
    Point2.render(f5);
    Point4.render(f5);
    Point5.render(f5);
    Point7.render(f5);
    Point8.render(f5);
    Point10.render(f5);
    Point11.render(f5);
    Inside1.render(f5);
    Inside2.render(f5);
    Inside3.render(f5);
    Inside4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
